import type { Rule } from "./sast-engine.ts";

type Spec = [id: string, title: string, cwe: number, category: string, pattern: RegExp, recommendation: string, options?: Partial<Pick<Rule, "severity" | "confidence" | "scope" | "exclude" | "description">>];
const groups: Record<string, Spec[]> = {
  SEC: [
    ["SEC100", "Токен загрузки PyPI", 798, "secrets", /\bpypi-AgEIcHlwaS5vcmc[A-Za-z0-9_-]{50,1000}(?![A-Za-z0-9_-])/, "Отзовите токен PyPI и проверьте опубликованные пакеты."],
    ["SEC101", "Токен Databricks", 798, "secrets", /\bdapi[a-f0-9]{32}(?:-\d)?\b/, "Отзовите токен Databricks и перенесите credentials в secret manager."],
    ["SEC102", "Токен DigitalOcean", 798, "secrets", /\bdop_v1_[a-f0-9]{64}\b/, "Отзовите токен DigitalOcean и проверьте изменения инфраструктуры."],
    ["SEC103", "Токен приложения Shopify", 798, "secrets", /\b(?:shpat|shpca|shppa)_[a-fA-F0-9]{32}\b/, "Отзовите токен Shopify и ограничьте permissions нового приложения."],
    ["SEC104", "Токен Doppler", 798, "secrets", /\bdp\.pt\.[A-Za-z0-9]{43}\b/, "Отзовите токен Doppler и проверьте доступ к хранилищу секретов."],
    ["SEC105", "API-токен Postman", 798, "secrets", /\bPMAK-[a-fA-F0-9]{24}-[a-fA-F0-9]{34}\b/, "Отзовите API-токен Postman и проверьте доступ к workspace."],
    ["SEC106", "API-токен Pulumi", 798, "secrets", /\bpul-[a-f0-9]{40}\b/, "Отзовите токен Pulumi и проверьте журналы операций со stacks."],
    ["SEC107", "Service account token Grafana", 798, "secrets", /\bglsa_[A-Za-z0-9]{32}_[a-fA-F0-9]{8}\b/, "Отзовите service account token Grafana и ограничьте права нового токена."],
    ["SEC108", "Пользовательский токен Sentry", 798, "secrets", /\bsntryu_[a-f0-9]{64}\b/, "Отзовите токен Sentry и исключите его из репозитория."],
    ["SEC109", "Webhook Slack в исходниках", 798, "secrets", /https:\/\/hooks\.slack\.com\/services\/T[A-Z0-9]{8,12}\/B[A-Z0-9]{8,12}\/[A-Za-z0-9]{24}/, "Перевыпустите webhook Slack и загружайте URL из защищённой конфигурации."],
    ["SEC110", "Токен Telegram Bot API", 798, "secrets", /\b\d{5,16}:A[A-Za-z0-9_-]{34}(?![A-Za-z0-9_-])/, "Перевыпустите токен бота через BotFather и исключите его из исходников."],
    ["SEC111", "Приватный ключ age", 321, "secrets", /\bAGE-SECRET-KEY-1[QPZRY9X8GF2TVDW0S3JN54KHCE6MUA7L]{58}\b/, "Смените приватный ключ age и проверьте доступ к зашифрованным данным."],
    ["SEC112", "Secret key 1Password", 798, "secrets", /\bA3-[A-Z0-9]{6}-[A-Z0-9]{6}-[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}\b/, "Перевыпустите secret key 1Password и проверьте доступ к vault."],
    ["SEC113", "Service account token 1Password", 798, "secrets", /\bops_eyJ[A-Za-z0-9+/]{250,1000}={0,3}/, "Отзовите service account token 1Password и проверьте обращения к секретам."],
    ["SEC114", "API-ключ Artifactory", 798, "secrets", /\bAKCp[A-Za-z0-9]{69}\b/, "Отзовите API-ключ Artifactory и используйте ограниченный access token."],
    ["SEC115", "Client secret Adobe", 798, "secrets", /\bp8e-[a-fA-F0-9]{32}\b/, "Перевыпустите client secret Adobe и перенесите его в secret store."],
  ],
  JS: [
    ["JS100", "jQuery HTML из HTTP-ввода", 79, "xss", /\.html\s*\(\s*(?:req|request)\.(?:body|query|params)\b/, "Используйте text() или очистку HTML по allowlist."],
    ["JS101", "Angular обходит проверку HTML", 79, "xss", /\.bypassSecurityTrustHtml\s*\(/, "Сохраняйте Angular sanitization; доверяйте только заранее проверенному HTML."],
    ["JS102", "Vue вставляет сырой HTML", 79, "xss", /\bv-html\s*=\s*["'][^"']+["']/, "Используйте интерполяцию текста Vue или очищайте HTML до v-html."],
    ["JS103", "Svelte вставляет сырой HTML", 79, "xss", /\{@html\s+[^}]+\}/, "Используйте штатную интерполяцию Svelte или очистку HTML по allowlist."],
    ["JS104", "Lodash template из HTTP-ввода", 1336, "injection", /\b_\.template\s*\(\s*(?:req|request)\.(?:body|query|params)\b/, "Используйте фиксированный шаблон и передавайте HTTP-ввод только как данные."],
    ["JS105", "MongoDB $where из HTTP-ввода", 943, "injection", /["']?\$where["']?\s*:\s*(?:req|request)\.(?:body|query|params)\b/, "Исключите $where и соберите типизированный фильтр из разрешённых полей."],
    ["JS106", "serialize-javascript отключает экранирование", 79, "xss", /\bserialize\s*\([^;\n]{0,250}\bunsafe\s*:\s*true\b/, "Оставьте unsafe выключенным и не вставляйте непроверенную сериализацию в HTML."],
    ["JS107", "Handlebars компилирует HTTP-ввод", 1336, "injection", /\b(?:Handlebars|handlebars)\.compile\s*\(\s*(?:req|request)\.(?:body|query|params)\b/, "Компилируйте статические шаблоны и передавайте пользовательские значения через контекст."],
    ["JS108", "EJS шаблон из HTTP-ввода", 1336, "injection", /\bejs\.render\s*\(\s*(?:req|request)\.(?:body|query|params)\b/, "Используйте фиксированный EJS template и отдельный объект данных."],
    ["JS109", "Устаревший password-based Cipher Node.js", 327, "crypto", /\b(?:crypto\.)?createCipher\s*\(/, "Используйте createCipheriv с AEAD, безопасным KDF и случайным nonce."],
    ["JS110", "Неинициализированный Buffer", 200, "validation", /\bBuffer\.allocUnsafe(?:Slow)?\s*\(/, "Используйте Buffer.alloc либо гарантированно заполняйте весь буфер до чтения или отправки."],
    ["JS111", "Короткий ключ подписи JWT", 321, "authentication", /\bjwt\.sign\s*\([^,\n]+,\s*["'][A-Za-z0-9_-]{1,15}["']\s*[,)]/, "Используйте стойкий ключ подписи из secret store; не задавайте короткий строковый секрет."],
    ["JS112", "Низкая стоимость bcrypt Node.js", 916, "crypto", /\bbcrypt\.(?:hash|hashSync|genSalt|genSaltSync)\s*\((?:[^,\n]+,\s*)?[1-9]\s*[,)]/, "Выберите стоимость bcrypt по измерениям нагрузки, обычно не ниже 10."],
    ["JS113", "Слишком мало итераций PBKDF2 Node.js", 916, "crypto", /\b(?:crypto\.)?pbkdf2(?:Sync)?\s*\([^,\n]+,[^,\n]+,\s*(?:[1-9]\d{0,2}|1000)\s*,/, "Выберите актуальную стоимость PBKDF2 для выбранного digest и проверяйте её по времени вычисления."],
    ["JS114", "Node.js разрешает TLS ниже 1.2", 326, "transport", /\bminVersion\s*:\s*["']TLSv1(?:\.1)?["']/, "Установите minVersion: 'TLSv1.2' или 'TLSv1.3'."],
    ["JS115", "Node.js отключает hostname check", 297, "transport", /\bcheckServerIdentity\s*:\s*\([^)]*\)\s*=>\s*(?:undefined|null)/, "Используйте стандартный tls.checkServerIdentity и корректный SAN сертификата."],
    ["JS116", "Legacy Electron remote module", 749, "configuration", /\benableRemoteModule\s*:\s*true\b/, "Отключите legacy remote module и предоставляйте минимальные IPC-команды."],
    ["JS117", "Electron разрешает mixed content", 319, "transport", /\ballowRunningInsecureContent\s*:\s*true\b/, "Отключите allowRunningInsecureContent и загружайте ресурсы через HTTPS."],
    ["JS118", "Загрузка скрипта jQuery из HTTP-ввода", 829, "injection", /(?<![\w$])(?:\$|jQuery)\.getScript\s*\(\s*(?:req|request)\.(?:body|query|params)\b/, "Загружайте только фиксированные доверенные скрипты с проверкой целостности."],
    ["JS119", "Отключена AngularJS SCE", 79, "xss", /(?<![\w$])\$sceProvider\.enabled\s*\(\s*false\s*\)/, "Сохраните SCE и применяйте проверку HTML, URL и других чувствительных контекстов."],
  ],
  PY: [
    ["PY100", "PyYAML unsafe_load", 502, "deserialization", /\byaml\.unsafe_load(?:_all)?\s*\(/, "Используйте yaml.safe_load и проверку структуры документа."],
    ["PY101", "jsonpickle создаёт объекты из JSON", 502, "deserialization", /\bjsonpickle\.decode\s*\(/, "Используйте json.loads с проверенной схемой без произвольного восстановления объектов."],
    ["PY102", "Десериализация marshal", 502, "deserialization", /\bmarshal\.loads?\s*\(/, "Не загружайте marshal из недоверенного источника; используйте обычный формат данных."],
    ["PY103", "Shelve использует Pickle", 502, "deserialization", /\bshelve\.open\s*\(/, "Открывайте только доверенные shelve-файлы; для внешних данных используйте SQLite или JSON."],
    ["PY104", "lxml снимает ограничения дерева", 400, "validation", /\b(?:etree\.)?XMLParser\s*\([^\n)]*\bhuge_tree\s*=\s*True\b/, "Оставьте huge_tree=False и ограничьте размер и глубину XML."],
    ["PY105", "defusedxml разрешает DTD", 611, "xxe", /\bforbid_dtd\s*=\s*False\b/, "Сохраните forbid_dtd=True для недоверенного XML и запретите внешние сущности."],
    ["PY106", "Python отключает hostname check", 297, "transport", /\bcheck_hostname\s*=\s*False\b/, "Включите check_hostname и используйте проверяемый SSL-контекст."],
    ["PY107", "Python выбирает устаревший TLS", 326, "transport", /\bssl\.PROTOCOL_(?:TLSv1|TLSv1_1|SSLv2|SSLv3)\b/, "Используйте PROTOCOL_TLS_CLIENT и minimum_version TLSv1_2."],
    ["PY108", "DES/ARC4 в Python", 327, "crypto", /\b(?:DES|DES3|ARC4)\.new\s*\(/, "Используйте AES-GCM или ChaCha20-Poly1305 с проверкой tag."],
    ["PY109", "Слабый размер RSA в Python", 326, "crypto", /\bRSA\.generate\s*\(\s*(?:512|768|1024)\s*[,)]/, "Используйте RSA не менее 2048 бит и актуальный криптографический протокол."],
    ["PY110", "Django extra с динамическим SQL", 89, "injection", /\.extra\s*\([^\n]*\bwhere\s*=\s*\[\s*f["']/, "Используйте ORM expressions и параметры SQL вместо f-строк в extra."],
    ["PY111", "Python cursor.execute с f-строкой", 89, "injection", /\b(?:cursor|cur)\.execute(?:many)?\s*\(\s*f["']/, "Передавайте значения вторым аргументом execute, SQL оставьте фиксированным."],
    ["PY112", "Flask-WTF отключает CSRF", 352, "csrf", /\bWTF_CSRF_ENABLED["']?\s*(?:=|:)\s*False\b/, "Включите WTF_CSRF_ENABLED для форм с cookie-аутентификацией."],
    ["PY113", "Flask отключает Jinja autoescape", 79, "xss", /\.jinja_env\.autoescape\s*=\s*False\b/, "Сохраните autoescape для HTML; текстовые форматы обрабатывайте отдельными шаблонами."],
    ["PY114", "aiohttp отключает TLS validation", 295, "transport", /\baiohttp\.TCPConnector\s*\([^\n)]*\bssl\s*=\s*False\b/, "Используйте проверяемый SSLContext и доверенный CA в TCPConnector."],
    ["PY115", "Paramiko исполняет HTTP-ввод", 78, "injection", /\.exec_command\s*\(\s*request\.(?:args|form|json|values)\b/, "Выбирайте фиксированную удалённую команду и проверяйте аргументы по allowlist."],
    ["PY116", "Сетевой listener logging.config", 94, "injection", /\blogging\.config\.listen\s*\(/, "Не принимайте произвольную logging-конфигурацию; используйте verify для проверки подписи.", { exclude: /\bverify\s*=\s*(?!None\b)[A-Za-z_]\w*/ }],
    ["PY117", "Python execvp выбирает команду из HTTP-ввода", 78, "injection", /\bos\.exec(?:vp|v|ve|vpe)\s*\(\s*request\.(?:args|form|json|values)\b/, "Фиксируйте исполняемый файл, передавайте проверенные аргументы отдельно."],
    ["PY118", "subprocess получает executable из HTTP-ввода", 78, "injection", /\bsubprocess\.(?:run|Popen|call)\s*\(\s*\[\s*request\.(?:args|form|json|values)\b/, "Не позволяйте HTTP-параметру выбирать бинарник; используйте allowlist операций."],
    ["PY119", "Legacy PickleSerializer для Django-сессии", 502, "deserialization", /\bSESSION_SERIALIZER\s*=\s*["'][^"']*PickleSerializer["']/, "Используйте JSONSerializer и перевыпустите сессии при возможной утечке ключа."],
  ],
  JAVA: [
    ["JAVA100", "XStream разрешает все типы", 502, "deserialization", /\.allowTypesByWildcard\s*\([^;\n]*"\*\*"/, "Задайте список разрешённых DTO; не разрешайте XStream wildcard '**'."],
    ["JAVA101", "Java XML расширяет entity references", 611, "xxe", /\.setExpandEntityReferences\s*\(\s*true\s*\)/, "Отключите entity expansion и запретите DTD/внешние сущности."],
    ["JAVA102", "Java XML разрешает DOCTYPE", 611, "xxe", /\.setFeature\s*\(\s*"http:\/\/apache\.org\/xml\/features\/disallow-doctype-decl"\s*,\s*false/, "Установите disallow-doctype-decl=true для недоверенных документов."],
    ["JAVA103", "XML parser включает XInclude", 611, "xxe", /\.setXIncludeAware\s*\(\s*true\s*\)/, "Отключите XInclude и запретите доступ XML-парсера к внешним ресурсам."],
    ["JAVA104", "StAX разрешает DTD", 611, "xxe", /\.setProperty\s*\(\s*(?:XMLInputFactory\.SUPPORT_DTD|"javax\.xml\.stream\.supportDTD")\s*,\s*(?:true|Boolean\.TRUE)/, "Установите XMLInputFactory.SUPPORT_DTD=false."],
    ["JAVA105", "StAX разрешает внешние сущности", 611, "xxe", /\.setProperty\s*\(\s*(?:XMLInputFactory\.IS_SUPPORTING_EXTERNAL_ENTITIES|"javax\.xml\.stream\.isSupportingExternalEntities")\s*,\s*(?:true|Boolean\.TRUE)/, "Установите IS_SUPPORTING_EXTERNAL_ENTITIES=false и ограничьте XML resolver."],
    ["JAVA106", "XSLT доступен любой внешний stylesheet", 611, "xxe", /\.setAttribute\s*\(\s*XMLConstants\.ACCESS_EXTERNAL_STYLESHEET\s*,\s*"all"/, "Установите ACCESS_EXTERNAL_STYLESHEET в пустую строку или строгий allowlist протоколов."],
    ["JAVA107", "JNDI доверяет remote codebase", 94, "injection", /\bSystem\.setProperty\s*\(\s*"com\.sun\.jndi\.(?:ldap|rmi)\.object\.trustURLCodebase"\s*,\s*"true"/, "Отключите trustURLCodebase и не разрешайте загрузку классов из удалённых источников."],
    ["JAVA108", "JNDI lookup из HTTP-ввода", 74, "injection", /\b(?:ctx|context|initialContext)\.lookup\s*\(\s*request\.getParameter\s*\(/, "Выбирайте JNDI-имя из фиксированного allowlist без пользовательского URL."],
    ["JAVA109", "Spring Expression из HTTP-ввода", 917, "injection", /\.parseExpression\s*\(\s*request\.getParameter\s*\(/, "Используйте фиксированные expressions и ограниченный SimpleEvaluationContext."],
    ["JAVA110", "Freemarker template из HTTP-ввода", 1336, "injection", /\bnew\s+Template\s*\([^;\n]{0,200}request\.getParameter\s*\(/, "Загружайте статические Freemarker-шаблоны и передавайте ввод как значения модели."],
    ["JAVA111", "Velocity исполняет HTTP-шаблон", 1336, "injection", /\bVelocity\.evaluate\s*\([^;\n]*request\.getParameter\s*\(/, "Не передавайте HTTP-ввод как исходный текст Velocity-шаблона."],
    ["JAVA112", "Слабый PBE-алгоритм Java", 327, "crypto", /\bSecretKeyFactory\.getInstance\s*\(\s*"PBEWithMD5AndDES"/, "Используйте современный KDF и AEAD вместо PBEWithMD5AndDES."],
    ["JAVA113", "Слабый алгоритм подписи Java", 327, "crypto", /\bSignature\.getInstance\s*\(\s*"(?:MD5withRSA|SHA1withRSA|SHA1withDSA)"/i, "Используйте RSA-PSS с SHA-256 или современную подпись Ed25519."],
    ["JAVA114", "HMAC-MD5 в Java", 327, "crypto", /\bMac\.getInstance\s*\(\s*"HmacMD5"/i, "Перейдите на HmacSHA256 с ключом достаточной длины."],
    ["JAVA115", "Java выбирает устаревший SSLContext", 326, "transport", /\bSSLContext\.getInstance\s*\(\s*"(?:SSL|SSLv3|TLSv1|TLSv1\.1)"/, "Выберите TLSv1.2 или TLSv1.3 и ограничьте версии протокола."],
    ["JAVA116", "Java отключает HttpOnly cookie", 1004, "authentication", /\.setHttpOnly\s*\(\s*false\s*\)/, "Включите HttpOnly для сессионных cookie, не предоставляйте их JavaScript."],
    ["JAVA117", "Java отключает Secure cookie", 614, "authentication", /\.setSecure\s*\(\s*false\s*\)/, "Включите Secure для cookie, содержащих данные сессии."],
    ["JAVA118", "Android WebView получает доступ к файлам", 200, "configuration", /\.setAllowFileAccess\s*\(\s*true\s*\)/, "Отключите file access для недоверенного WebView и используйте WebViewAssetLoader."],
    ["JAVA119", "Android WebView открыт отладчику", 489, "configuration", /\bWebView\.setWebContentsDebuggingEnabled\s*\(\s*true\s*\)/, "Отключите WebView debugging в release-сборке."],
  ],
  PHP: [
    ["PHP100", "Legacy create_function исполняет код", 95, "injection", /\bcreate_function\s*\(/i, "Замените legacy create_function статической closure-функцией."],
    ["PHP101", "eval в PHP", 95, "injection", /\beval\s*\(/i, "Удалите eval и используйте парсер данных или список разрешённых операций."],
    ["PHP102", "PHP assert с HTTP-строкой", 95, "injection", /\bassert\s*\(\s*\$_(?:GET|POST|REQUEST)\b/i, "Не используйте legacy string assertions; валидируйте ввод явными проверками."],
    ["PHP103", "Вызов функции по HTTP-параметру", 94, "injection", /\bcall_user_func(?:_array)?\s*\(\s*\$_(?:GET|POST|REQUEST)\b/i, "Выбирайте обработчик из фиксированной карты разрешённых функций."],
    ["PHP104", "preg_replace callback из HTTP-ввода", 94, "injection", /\bpreg_replace_callback\s*\([^,\n]+,\s*\$_(?:GET|POST|REQUEST)\b/i, "Используйте фиксированный callback вместо имени из пользовательского запроса."],
    ["PHP105", "Phar десериализует метаданные", 502, "deserialization", /->getMetadata\s*\(/i, "Для недоверенного Phar используйте getMetadata(['allowed_classes' => false]) и проверьте структуру метаданных.", { exclude: /["']allowed_classes["']\s*=>\s*false\b/i }],
    ["PHP106", "extract импортирует HTTP-поля в scope", 915, "authorization", /\bextract\s*\(\s*\$_(?:GET|POST|REQUEST)\b/i, "Читайте разрешённые поля явно; не превращайте HTTP-параметры в локальные переменные."],
    ["PHP107", "parse_str без массива результата", 915, "validation", /\bparse_str\s*\(\s*\$_(?:GET|POST|REQUEST)\[[^\]\n]+\]\s*\)/i, "В legacy PHP передавайте отдельный массив результата и проверяйте разрешённые ключи."],
    ["PHP108", "Вывод HTTP-ввода без HTML-экранирования", 79, "xss", /\b(?:echo|print)\s+\$_(?:GET|POST|REQUEST)\b/i, "Используйте htmlspecialchars с ENT_QUOTES и корректной кодировкой для HTML-текста."],
    ["PHP109", "PHP file_get_contents из HTTP-URL", 918, "ssrf", /\bfile_get_contents\s*\(\s*\$_(?:GET|POST|REQUEST)\b/i, "Разрешайте только известные назначения, блокируйте локальные сети и опасные схемы."],
    ["PHP110", "cURL URL из HTTP-параметра", 918, "ssrf", /\bCURLOPT_URL\s*(?:,|=>)\s*\$_(?:GET|POST|REQUEST)\b/i, "Проверяйте URL, DNS/IP и каждое перенаправление по allowlist."],
    ["PHP111", "PHP readfile отдаёт HTTP-путь", 22, "validation", /\breadfile\s*\(\s*\$_(?:GET|POST|REQUEST)\b/i, "Выбирайте файл внутри фиксированного каталога по безопасному идентификатору."],
    ["PHP112", "PHP move_uploaded_file выбирает HTTP-путь", 434, "validation", /\bmove_uploaded_file\s*\([^,\n]+,\s*\$_(?:GET|POST|REQUEST)\b/i, "Задавайте серверное имя и каталог загрузки, проверяйте тип и исключите исполнение файлов."],
    ["PHP113", "Слабый bcrypt cost в PHP", 916, "crypto", /\bpassword_hash\s*\([^;\n]*["']cost["']\s*=>\s*[1-9]\s*[,\]]/, "Выбирайте bcrypt cost по измерениям нагрузки, обычно не ниже 10."],
    ["PHP114", "Отключён strict mode PHP-сессий", 384, "authentication", /\bini_set\s*\(\s*["']session\.use_strict_mode["']\s*,\s*(?:["']0["']|0|false)\s*\)/i, "Включите session.use_strict_mode и обновляйте ID после аутентификации."],
    ["PHP115", "PHP возвращает session ID в URL", 598, "authentication", /\bini_set\s*\(\s*["']session\.use_trans_sid["']\s*,\s*(?:["']1["']|1|true)\s*\)/i, "Отключите trans_sid и передавайте ID только через защищённый cookie."],
  ],
};

Object.assign(groups, {
  GO: [
    ["GO100", "Токен Go из math/rand", 338, "crypto", /\b(?:token|secret|nonce|password)\w*\s*:?=\s*rand\.(?:Intn|Int63|Uint32|Uint64)\s*\(/i, "Используйте crypto/rand для секретов; проверьте импорт и источник RNG."],
    ["GO101", "Go JWT без проверки claims", 613, "authentication", /\bjwt\.WithoutClaimsValidation\s*\(/, "Проверяйте срок действия, issuer и audience после криптографической проверки JWT."],
    ["GO102", "Go JWT разрешает алгоритм none", 347, "authentication", /\bjwt\.WithValidMethods\s*\([^\n]*"none"/, "Разрешайте только ожидаемые алгоритмы подписи, исключите none."],
    ["GO103", "Go JWT использует UnsafeAllowNoneSignatureType", 347, "authentication", /\bjwt\.UnsafeAllowNoneSignatureType\b/, "Не принимайте JWT без подписи; используйте фиксированный signing method."],
    ["GO104", "Legacy gRPC без TLS", 319, "transport", /\bgrpc\.WithInsecure\s*\(/, "Используйте grpc.WithTransportCredentials с проверяемым TLS."],
    ["GO105", "gRPC insecure credentials", 319, "transport", /\binsecure\.NewCredentials\s*\(/, "Не передавайте чувствительные данные по plaintext gRPC; настройте TLS credentials."],
    ["GO106", "Go ограничивает TLS устаревшей версией", 326, "transport", /\bMaxVersion\s*:\s*tls\.Version(?:TLS10|TLS11|SSL30)\b/, "Разрешите TLS 1.2/1.3 и уберите устаревший MaxVersion."],
    ["GO107", "Go XML отключает strict parsing", 20, "validation", /\b(?:decoder|dec)\.Strict\s*=\s*false\b/, "Сохраняйте strict XML parsing и валидируйте структуру недоверенного документа."],
    ["GO108", "Go redirect из HTTP-ввода", 601, "validation", /\bhttp\.Redirect\s*\([^\n]*\br\.(?:URL\.Query\s*\(|FormValue\s*\()/, "Разрешайте только локальные маршруты или известные URL назначения."],
    ["GO109", "Go ServeFile из HTTP-пути", 22, "validation", /\bhttp\.ServeFile\s*\([^\n]*\br\.(?:URL\.Query\s*\(|FormValue\s*\()/, "Выбирайте файлы по allowlist внутри фиксированного каталога."],
    ["GO110", "Go RemoveAll из HTTP-пути", 73, "validation", /\bos\.RemoveAll\s*\(\s*r\.(?:URL\.Query\s*\(|FormValue\s*\()/, "Не позволяйте запросу выбирать каталог удаления; проверяйте владельца и нормализованный путь."],
    ["GO111", "Go выводит TLS key log в stdout", 532, "configuration", /\bKeyLogWriter\s*:\s*os\.(?:Stdout|Stderr)\b/, "Отключите TLS key logging в production и защищайте диагностические ключи."],
    ["GO112", "Низкая стоимость bcrypt Go", 916, "crypto", /\bbcrypt\.GenerateFromPassword\s*\([^,\n]+,\s*[1-9]\s*\)/, "Выберите стоимость bcrypt по измерениям нагрузки, обычно не ниже 10."],
    ["GO113", "SSH Go доверяет любой user authority", 295, "transport", /\bIsUserAuthority\s*:\s*func\s*\([^)]*\)\s*bool\s*\{\s*return\s+true\s*\}/, "Проверяйте user certificate authority по списку доверенных ключей.", { scope: "file" }],
  ],
  CS: [
    ["CS100", "Legacy .NET разрешает DTD", 611, "xxe", /\bProhibitDtd\s*=\s*false\b/, "Используйте DtdProcessing.Prohibit и отключённый внешний XmlResolver."],
    ["CS101", "XML resolver .NET получает доступ к URL", 611, "xxe", /\bXmlResolver\s*=\s*new\s+XmlUrlResolver\s*\(/, "Для недоверенного XML установите XmlResolver=null и запретите внешние ресурсы."],
    ["CS102", "XSLT .NET включает trusted features", 94, "injection", /\bXsltSettings\.TrustedXslt\b/, "Используйте XsltSettings.Default и запретите script/document() для недоверенного XSLT."],
    ["CS103", "ASP.NET отключает request validation", 79, "xss", /\[\s*ValidateInput\s*\(\s*false\s*\)\s*\]/, "Сохраняйте request validation и контекстное экранирование пользовательского вывода."],
    ["CS104", "Отключён MAC ASP.NET ViewState", 345, "authentication", /\bEnableViewStateMac\s*=\s*false\b/i, "Включите EnableViewStateMac и защитите machine key.", { severity: "critical" }],
    ["CS105", "ViewState не шифруется", 200, "configuration", /\bViewStateEncryptionMode\s*=\s*(?:ViewStateEncryptionMode\.)?Never\b/, "Не храните секреты в ViewState; при чувствительных данных включите шифрование."],
    ["CS106", "ASP.NET отключает event validation", 20, "validation", /\bEnableEventValidation\s*=\s*false\b/i, "Включите event validation и проверяйте допустимые значения postback."],
    ["CS107", "CookieOptions отключает HttpOnly", 1004, "authentication", /\bHttpOnly\s*=\s*false\b/, "Включите HttpOnly для сессионных cookie."],
    ["CS108", "CookieOptions отключает Secure", 614, "authentication", /\bSecure\s*=\s*false\b/, "Установите Secure=true для cookie с данными сессии."],
    ["CS109", "JWT middleware разрешает HTTP metadata", 319, "transport", /\bRequireHttpsMetadata\s*=\s*false\b/, "Загружайте metadata и signing keys только по проверяемому HTTPS."],
    ["CS110", "JWT отключает проверку signing key", 345, "authentication", /\bValidateIssuerSigningKey\s*=\s*false\b/, "Проверяйте допустимый signing key; этот флаг не заменяет проверку подписи JWT."],
    ["CS111", "JWT не требует подписанного токена", 347, "authentication", /\bRequireSignedTokens\s*=\s*false\b/, "Установите RequireSignedTokens=true и фиксируйте разрешённые алгоритмы.", { severity: "critical" }],
    ["CS112", "JWT отключает проверку lifetime", 613, "authentication", /\bValidateLifetime\s*=\s*false\b/, "Проверяйте exp/nbf и задайте ограниченный clock skew."],
    ["CS113", "JWT отключает проверку audience", 346, "authentication", /\bValidateAudience\s*=\s*false\b/, "Включите ValidateAudience и укажите audience приложения."],
    ["CS114", "JWT отключает проверку issuer", 346, "authentication", /\bValidateIssuer\s*=\s*false\b/, "Включите ValidateIssuer и укажите доверенного издателя токенов."],
    ["CS115", "Слабый RSA-ключ .NET", 326, "crypto", /\bnew\s+RSACryptoServiceProvider\s*\(\s*(?:512|768|1024)\s*\)/, "Создавайте RSA-ключ не менее 2048 бит с актуальными параметрами подписи."],
  ],
  RB: [
    ["RB100", "Psych unsafe_load_file", 502, "deserialization", /\b(?:YAML|Psych)\.unsafe_load_file\s*\(/, "Используйте safe_load_file с ограниченными классами и проверкой структуры."],
    ["RB101", "Oj object_load восстанавливает Ruby-объекты", 502, "deserialization", /\bOj\.object_load\s*\(/, "Используйте Oj.strict_load для данных, не восстанавливайте произвольные классы."],
    ["RB102", "Ruby JSON разрешает additions", 502, "deserialization", /\bJSON\.(?:load|parse)\s*\([^\n]*\bcreate_additions\s*:\s*true\b/, "Установите create_additions:false и проверяйте JSON по схеме."],
    ["RB103", "Kernel.open из HTTP-ввода", 78, "injection", /\b(?:Kernel\.)?open\s*\(\s*params\[/, "Используйте File.open с проверенным локальным путём, исключите pipe-команды."],
    ["RB104", "ERB template из HTTP-ввода", 1336, "injection", /\bERB\.new\s*\(\s*params\[/, "Используйте статический ERB template и отдельный binding с данными."],
    ["RB105", "Ruby задаёт устаревший min TLS", 326, "transport", /\bmin_version\s*=\s*OpenSSL::SSL::TLS1(?:_1)?_VERSION\b/, "Установите min_version TLS1_2_VERSION или TLS1_3_VERSION."],
    ["RB106", "Rails session cookie без HttpOnly", 1004, "authentication", /\bsession_store\b[^\n]*\bhttponly\s*:\s*false\b/, "Включите httponly для Rails session store и задайте Secure/SameSite."],
    ["RB107", "Rails find_by_sql с интерполяцией", 89, "injection", /\.find_by_sql\s*\(\s*"[^"\n]*#\{/, "Используйте параметризованный запрос или ActiveRecord query API."],
    ["RB108", "Rails order из HTTP-ввода", 89, "injection", /\.order\s*\(\s*params\[/, "Выбирайте колонку и направление сортировки из серверного allowlist."],
    ["RB109", "Rails render inline из HTTP-ввода", 1336, "injection", /\brender\s+(?:\(\s*)?inline\s*:\s*params\[/, "Не компилируйте params как шаблон; используйте фиксированный view."],
    ["RB110", "Ruby send выбирает HTTP-метод", 94, "injection", /\.(?:send|public_send)\s*\(\s*params\[/, "Разрешайте dispatch только через карту известных операций."],
    ["RB111", "Rails send_file из HTTP-параметра", 22, "validation", /\bsend_file\s*(?:\(\s*)?params\[/, "Выбирайте файл внутри фиксированного каталога и проверяйте права пользователя."],
  ],
  RS: [
    ["RS100", "DES в Rust", 327, "crypto", /\b(?:des::)?(?:Des|TdesEde3)::new(?:_from_slice)?\s*\(/, "Используйте AES-GCM или ChaCha20-Poly1305 с уникальным nonce."],
    ["RS101", "Rust OpenSSL не проверяет hostname", 297, "transport", /\.set_verify_hostname\s*\(\s*false\s*\)/, "Включите проверку hostname и используйте корректный SAN сертификата."],
    ["RS102", "Actix CORS разрешает любой origin", 942, "authorization", /\bCors::permissive\s*\(/, "Задайте явный allowlist origins и ограничьте credentialed-запросы."],
    ["RS103", "Actix раздаёт корневой каталог", 552, "configuration", /\bFiles::new\s*\(\s*"[^"]*"\s*,\s*"(?:\.|\/)"\s*\)/, "Раздавайте отдельный каталог публичных файлов, не текущий каталог или корень узла."],
    ["RS104", "Rocket использует нулевой secret key", 321, "authentication", /\bSecretKey::from\s*\(\s*&\[\s*0\s*;\s*64\s*\]\s*\)/, "Сгенерируйте случайный SecretKey вне исходников и защищайте session cookies."],
    ["RS105", "Rust JWT отключает exp validation", 613, "authentication", /\b(?:validation|validator)\.validate_exp\s*=\s*false\b/, "Включите проверку exp и ограничьте clock skew."],
    ["RS106", "Rust JWT отключает подпись", 347, "authentication", /\.insecure_disable_signature_validation\s*\(/, "Используйте проверку подписи JWT и фиксированный список алгоритмов.", { severity: "critical" }],
    ["RS107", "Rust OpenSSL создаёт слабый RSA", 326, "crypto", /\b(?:openssl::rsa::)?Rsa::generate\s*\(\s*(?:512|768|1024)\s*\)/, "Используйте RSA не менее 2048 бит."],
    ["RS108", "Низкая память Argon2 Rust", 916, "crypto", /\bargon2::Params::new\s*\(\s*(?:8|16|32|64|128|256|512|1024)\s*,/, "Выберите memory/time cost Argon2 по актуальным требованиям и измерениям нагрузки."],
    ["RS109", "RSA PKCS1 v1.5 encryption Rust", 780, "crypto", /\brsa::Pkcs1v15Encrypt\b/, "Используйте RSA-OAEP и исключите oracle по ответам ошибок дешифрования."],
  ],
  SWIFT: [
    ["SWIFT100", "Credential в UserDefaults", 922, "authentication", /\bUserDefaults\.standard\.set\s*\(\s*(?:password|token|secret|accessToken|refreshToken)\b/, "Храните credentials в Keychain с подходящим уровнем доступности."],
    ["SWIFT101", "Секрет в NSLog", 532, "configuration", /\bNSLog\s*\([^\n]*(?:password|accessToken|refreshToken|secret)\b/, "Удалите секреты из NSLog и применяйте централизованное маскирование."],
    ["SWIFT102", "WebView HTML из динамического значения", 79, "xss", /\.loadHTMLString\s*\(\s*(?:userHtml|userInput|requestBody)\b/, "Не загружайте недоверенный HTML в привилегированный WebView; очистите его и ограничьте навигацию."],
    ["SWIFT103", "WKWebView разрешает file URL access", 200, "configuration", /\.setValue\s*\(\s*true\s*,\s*forKey\s*:\s*"allowFileAccessFromFileURLs"/, "Не включайте доступ file URL для WebView с недоверенным содержимым."],
    ["SWIFT104", "TLS trust exceptions в Swift", 295, "transport", /\bSecTrustSetExceptions\s*\(/, "Не принимайте произвольные trust exceptions; используйте системную проверку TLS."],
    ["SWIFT105", "Swift задаёт слабый RSA-ключ", 326, "crypto", /\bkSecAttrKeyType\s*:\s*kSecAttrKeyTypeRSA[^\n]{0,250}\bkSecAttrKeySizeInBits\s*:\s*(?:512|768|1024)\b/, "Задайте RSA key size не менее 2048 бит."],
    ["SWIFT106", "CommonCrypto выбирает DES", 327, "crypto", /\bkCCAlgorithm(?:DES|3DES|RC2|RC4)\b/, "Используйте современный AEAD-алгоритм и проверяйте authentication tag."],
    ["SWIFT107", "Swift отключает secure coding", 502, "deserialization", /\brequiresSecureCoding\s*=\s*false\b/, "Включите requiresSecureCoding и задайте разрешённые классы для unarchiver."],
    ["SWIFT108", "GRDB SQL через Swift-интерполяцию", 89, "injection", /\.execute\s*\(\s*sql\s*:\s*"[^"\n]*\\\(/, "Используйте GRDB arguments и placeholders вместо Swift-интерполяции."],
    ["SWIFT109", "Общедоступные POSIX permissions Swift", 732, "configuration", /\bposixPermissions\s*:\s*0o(?:777|666)\b/, "Назначайте минимальные permissions для файлов и каталогов."],
  ],
  SCALA: [
    ["SCALA100", "Scala ToolBox выполняет код", 95, "injection", /\b(?:toolbox|toolBox|tb)\.eval\s*\(/, "Не выполняйте недоверенное AST; используйте фиксированную карту операций."],
    ["SCALA101", "Scala ToolBox разбирает HTTP-код", 95, "injection", /\b(?:toolbox|toolBox|tb)\.parse\s*\(\s*(?:request|req)\./, "Не превращайте HTTP-ввод в компилируемый Scala-код."],
    ["SCALA102", "Twirl HtmlFormat.raw", 79, "xss", /\bHtmlFormat\.raw\s*\(/, "Используйте HtmlFormat.escape; очищайте HTML перед созданием raw-фрагмента."],
    ["SCALA103", "Slick вставляет SQL literal", 89, "injection", /\bsqlu?"[^"\n]*#\$/, "Используйте обычную Slick-интерполяцию bind-параметров вместо '#$'."],
    ["SCALA104", "Akka CORS разрешает все origins", 942, "authorization", /\.withAllowedOrigins\s*\(\s*HttpOriginRange\.\*\s*\)/, "Укажите ограниченный набор origins для Akka HTTP CORS."],
    ["SCALA105", "Scala Process запускает shell", 78, "injection", /\bProcess\s*\(\s*Seq\s*\(\s*"(?:sh|bash)"\s*,\s*"-c"/, "Передавайте executable и аргументы без оболочки."],
    ["SCALA106", "Scala URL из HTTP-ввода", 918, "ssrf", /\bSource\.fromURL\s*\(\s*(?:request|req)\./, "Проверяйте URL и резолвинг IP по allowlist назначений."],
    ["SCALA107", "Play redirect из HTTP-ввода", 601, "validation", /\bRedirect\s*\(\s*request\.getQueryString\s*\(/, "Перенаправляйте только на разрешённые локальные пути."],
    ["SCALA108", "Play отдаёт HTTP-путь к файлу", 22, "validation", /\.sendFile\s*\(\s*new\s+File\s*\(\s*request\./, "Выбирайте файл из контролируемого каталога и проверяйте разрешения."],
    ["SCALA109", "Play WS разрешает слабые шифры", 326, "transport", /\ballowWeakCiphers\s*=\s*true\b/, "Отключите allowWeakCiphers и используйте современный TLS cipher suite."],
  ],
  SH: [
    ["SH100", "Shell trace может раскрыть секреты", 532, "configuration", /^\s*set\s+-[A-Za-z]*x[A-Za-z]*(?:\s|$)/m, "Отключайте xtrace перед обработкой секретов и не сохраняйте чувствительные аргументы в CI logs."],
    ["SH101", "Пароль curl в argv", 214, "secrets", /\bcurl\b[^\n]*\s(?:-u|--user)\s+["'][^"'\n:]+:[^"'\n]+["']/, "Используйте защищённый netrc или механизм credentials вне аргументов процесса."],
    ["SH102", "Shell использует DES encryption", 327, "crypto", /\bopenssl\s+enc\b[^\n]*\s-(?:des|des-cbc|des-ede3-cbc)\b/, "Используйте проверенный формат AEAD вместо openssl enc с DES."],
    ["SH103", "Shell digest MD5", 327, "crypto", /\bopenssl\s+dgst\b[^\n]*\s-md5\b/, "Для криптографической целостности используйте SHA-256 или современную подпись."],
    ["SH104", "Shell создаёт слабый RSA-ключ", 326, "crypto", /\bopenssl\s+genrsa\b[^\n]*\s(?:512|768|1024)(?=\s|$)/, "Создавайте RSA-ключ не менее 2048 бит и защищайте приватный файл."],
    ["SH105", "Shell устанавливает setuid", 250, "configuration", /\bchmod\s+(?:u\+s|[2467][0-7]{3})\b/, "Не назначайте setuid без проверенной необходимости; используйте минимальные привилегии."],
    ["SH106", "Shell разрешает world-write", 732, "configuration", /\bchmod\s+(?:o\+w|a\+w)\b/, "Не давайте запись всем пользователям; назначайте отдельную группу владельца."],
    ["SH107", "Docker CLI добавляет SYS_ADMIN", 250, "configuration", /\bdocker\s+run\b[^\n]*--cap-add(?:=|\s+)(?:SYS_ADMIN|ALL)\b/, "Удалите SYS_ADMIN/ALL и выдайте только необходимые capabilities."],
    ["SH108", "Docker CLI монтирует корень хоста", 250, "configuration", /\bdocker\s+run\b[^\n]*\s(?:-v|--volume)\s+["']?\/:/, "Не монтируйте корень узла; используйте выделенный volume с ограниченными правами."],
    ["SH109", "Docker CLI получает host network", 250, "configuration", /\bdocker\s+run\b[^\n]*--network(?:=|\s+)host\b/, "Используйте отдельную сеть контейнера и явно публикуйте нужные порты."],
    ["SH110", "curl передаёт credentials через redirect", 522, "transport", /\bcurl\b[^\n]*--location-trusted\b/, "Используйте --location с проверкой назначения; не пересылайте credentials произвольным хостам."],
    ["SH111", "tar разрешает абсолютные пути", 22, "validation", /\btar\b[^\n]*--absolute-names\b/, "Распаковывайте недоверенные архивы с проверкой путей и без --absolute-names."],
  ],
  CFG: [
    ["CFG100", "Windows контейнер получает hostProcess", 250, "configuration", /\bhostProcess\s*:\s*true\b/i, "Отключите hostProcess вне обоснованных системных workloads."],
    ["CFG101", "Pod автоматически получает API token", 522, "configuration", /\bautomountServiceAccountToken\s*:\s*true\b/i, "Выключите автоматический token mount, если workload не использует Kubernetes API."],
    ["CFG102", "Root filesystem контейнера допускает запись", 732, "configuration", /\breadOnlyRootFilesystem\s*:\s*false\b/i, "Используйте readOnlyRootFilesystem=true и отдельные volumes для необходимых записей."],
    ["CFG103", "Kubernetes отключает proc masking", 250, "configuration", /\bprocMount\s*:\s*["']?Unmasked\b/, "Используйте procMount: Default и ограничьте доступ к procfs."],
    ["CFG104", "Pod разделяет process namespace", 250, "configuration", /\bshareProcessNamespace\s*:\s*true\b/i, "Разделяйте process namespace только для проверенных контейнеров с одинаковой границей доверия."],
    ["CFG105", "Контейнер получает NET_RAW", 250, "configuration", /\b(?:cap_add|add)\s*:\s*\[[^\]\n]*\bNET_RAW\b/, "Удалите NET_RAW, если приложение не требует raw sockets."],
    ["CFG106", "Dashboard разрешает skip login", 306, "authentication", /--enable-skip-login\b/, "Отключите skip login и настройте проверяемую аутентификацию Dashboard."],
    ["CFG107", "Опубликован Docker API port 2375", 306, "configuration", /["']?(?:0\.0\.0\.0:)?2375:2375(?:\/tcp)?["']?/, "Не публикуйте plaintext Docker API; используйте Unix socket или защищённый TLS endpoint."],
    ["CFG108", "Docker доверяет insecure registry", 319, "transport", /"insecure-registries"\s*:\s*\[\s*"[^"\n]+"/, "Используйте HTTPS registry с доверенным сертификатом."],
    ["CFG109", "S3 отключает Public Access Block", 284, "authorization", /\b(?:BlockPublicAcls|IgnorePublicAcls|BlockPublicPolicy|RestrictPublicBuckets)["']?\s*:\s*false\b/i, "Включите Public Access Block; публичный доступ разрешайте только по утверждённой политике."],
    ["CFG110", "Cloud storage без encryption at rest", 311, "crypto", /\bStorageEncrypted["']?\s*:\s*false\b/i, "Включите encryption at rest с защищённым KMS-ключом."],
    ["CFG111", "База данных публично доступна", 284, "authorization", /\bPubliclyAccessible["']?\s*:\s*true\b/i, "Закройте публичный доступ к БД и ограничьте сетевые источники."],
    ["CFG112", "KMS key rotation отключён", 320, "crypto", /\bEnableKeyRotation["']?\s*:\s*false\b/i, "Включите поддерживаемую rotation policy и контролируйте жизненный цикл ключей."],
    ["CFG113", "Database deletion protection отключён", 1188, "configuration", /\bDeletionProtection["']?\s*:\s*false\b/i, "Включите deletion protection для production-БД и ограничьте право удаления."],
    ["CFG114", "Redshift не требует SSL", 319, "transport", /\brequire_ssl["']?\s*[:=]\s*false\b/i, "Включите require_ssl и проверяйте сертификат при подключении."],
    ["CFG115", "Azure разрешает публичные blobs", 284, "authorization", /\ballowBlobPublicAccess["']?\s*[:=]\s*true\b/i, "Отключите public blob access и используйте ограниченные permissions/SAS."],
    ["CFG116", "Elasticsearch отключает security", 306, "authentication", /\bxpack\.security\.enabled\s*[:=]\s*false\b/i, "Включите authentication/authorization Elasticsearch и TLS для сетевого доступа."],
    ["CFG117", "MongoDB отключает authorization", 306, "authentication", /\bauthorization\s*:\s*["']?disabled\b/i, "Установите authorization: enabled и ограничьте роли пользователей."],
    ["CFG118", "Redis отключает protected mode", 306, "authentication", /^\s*protected-mode\s*(?:[:=]\s*)?no\b/im, "Включите protected-mode и настройте ACL, bind и TLS."],
    ["CFG119", "MySQL запускается без grants", 306, "authentication", /^\s*(?:--)?skip-grant-tables(?:\s|=|$)/im, "Удалите skip-grant-tables из production-конфигурации."],
    ["CFG120", "Nginx не проверяет upstream TLS", 295, "transport", /\bproxy_ssl_verify\s+off\s*;/i, "Включите proxy_ssl_verify и настройте trusted CA/hostname upstream."],
    ["CFG121", "HAProxy не проверяет backend TLS", 295, "transport", /^\s*server\s+[^\n]*\bssl\b[^\n]*\bverify\s+none\b/im, "Используйте verify required и доверенный CA для backend TLS."],
    ["CFG122", "Nginx публикует directory listing", 548, "configuration", /\bautoindex\s+on\s*;/i, "Отключите autoindex для непубличных каталогов и исключите секретные файлы."],
    ["CFG123", "Spring Actuator публикует все endpoints", 200, "configuration", /\bmanagement\.endpoints\.web\.exposure\.include\s*[:=]\s*["']?\*["']?/, "Публикуйте только необходимые Actuator endpoints с аутентификацией."],
  ],
} satisfies Record<string, Spec[]>);

const categoryInfo: Record<string, [string, string]> = {
  secrets: ["A07:2021", "Найден узнаваемый формат секрета. Проверьте утечку и отзовите credential; сетевой проверки действительности не выполняется."],
  xss: ["A03:2021", "При недоверенных данных возможен XSS; проверьте источник и контекст экранирования."],
  injection: ["A03:2021", "Недоверенные данные или опасная настройка могут изменить выполняемую операцию. Проверьте границу доверия."],
  deserialization: ["A08:2021", "Загрузка недоверенных объектов может выполнить код или нарушить ограничения ресурсов. Проверьте происхождение данных."],
  crypto: ["A02:2021", "Параметр или алгоритм требует проверки для использования в защитных механизмах."],
  transport: ["A02:2021", "Настройка ослабляет защиту соединения. Проверьте протокол и аутентификацию другой стороны."],
  xxe: ["A05:2021", "Настройка XML может открыть доступ к внешним ресурсам или расширению сущностей. Проверьте все ограничения parser/resolver."],
  csrf: ["A01:2021", "Отключена защита от поддельных запросов. При cookie-аутентификации нужна независимая CSRF-проверка."],
  authentication: ["A07:2021", "Настройка требует проверки защиты credentials, сессий или аутентификации."],
  authorization: ["A01:2021", "Настройка может расширить доступ к данным или операциям. Проверьте требуемые permissions."],
  validation: ["A01:2021", "Вызов требует проверки входных данных, путей, объёма или результата до использования."],
  configuration: ["A05:2021", "Найдена настройка, требующая проверки в production и ограничения предоставленных возможностей."],
  ssrf: ["A10:2021", "Внешний ввод определяет сетевое назначение. Проверьте адрес, схему и перенаправления."],
};

export function createExpansionRules(allLanguages: string[]): Rule[] {
  const languages: Record<string, string[]> = {
    SEC: allLanguages, JS: ["javascript", "typescript"], PY: ["python"], JAVA: ["java", "kotlin"],
    PHP: ["php"], GO: ["go"], CS: ["csharp"], RB: ["ruby"], RS: ["rust"],
    SWIFT: ["swift"], SCALA: ["scala"], SH: ["shell"], CFG: ["config"],
  };
  const criticalCwes = new Set([78, 89, 94, 95, 347, 917, 1336]);
  const highCategories = new Set(["xss", "xxe", "deserialization", "ssrf", "transport", "injection"]);
  return Object.entries(groups).flatMap(([group, specs]) => specs.map(([id, title, cwe, category, pattern, recommendation, options]) => ({
    id, title, cwe: `CWE-${cwe}`, category, pattern, recommendation, languages: languages[group],
    description: `${title}. ${categoryInfo[category][1]}`,
    owasp: categoryInfo[category][0],
    severity: group === "SEC" || criticalCwes.has(cwe) ? "critical" as const : highCategories.has(category) || cwe === 306 ? "high" as const : "medium" as const,
    confidence: group === "SEC" ? "high" as const : "medium" as const,
    references: [`https://cwe.mitre.org/data/definitions/${cwe}.html`], ...options,
  })));
}
