import type { Rule, Severity } from "./sast-engine.ts";

// Fourth catalog: stable IDs starting at 300. Regex-based review signals.
type Spec = [id: string, title: string, cwe: number, category: string, pattern: RegExp, recommendation: string, reference?: string];
const groups: Record<string, Spec[]> = {
  SEC: [
    ["SEC300", "Personal access token Airtable", 798, "secrets", /\bpat[A-Za-z0-9]{14}\.[a-f0-9]{64}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC301", "Reference token Artifactory", 798, "secrets", /\bcmVmd[A-Za-z0-9]{59}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC302", "Access key Authress", 798, "secrets", /\b(?:sc|ext|scauth|authress)_[A-Za-z0-9]{5,30}\.[A-Za-z0-9]{4,6}\.acc[_-][A-Za-z0-9-]{10,32}\.[A-Za-z0-9+/_=-]{30,120}(?![A-Za-z0-9+/_=-])/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC303", "Long-lived API key Amazon Bedrock", 798, "secrets", /\bABSK[A-Za-z0-9+/]{109,269}={0,2}(?![A-Za-z0-9+/=])/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC304", "Cloud secret key ClickHouse", 798, "secrets", /\b4b1d[A-Za-z0-9]{38}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC305", "Deploy token Clojars", 798, "secrets", /\bCLOJARS_[A-Za-z0-9]{60}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC306", "Origin CA key Cloudflare", 798, "secrets", /\bv1\.0-[a-f0-9]{24}-[a-f0-9]{146}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC307", "OAuth access token DigitalOcean", 798, "secrets", /\bdoo_v1_[a-f0-9]{64}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC308", "OAuth refresh token DigitalOcean", 798, "secrets", /\bdor_v1_[a-f0-9]{64}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC309", "Live API token Duffel", 798, "secrets", /\bduffel_live_[A-Za-z0-9_=-]{43}(?![A-Za-z0-9_=-])/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC310", "API token Dynatrace", 798, "secrets", /\bdt0c01\.[A-Za-z0-9]{24}\.[A-Za-z0-9]{64}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC311", "Production API token EasyPost", 798, "secrets", /\bEZAK[A-Za-z0-9]{54}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC312", "Access token Fly.io", 798, "secrets", /\bfo1_[A-Za-z0-9_-]{43}(?![A-Za-z0-9_-])/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC313", "API token Frame.io", 798, "secrets", /\bfio-u-[A-Za-z0-9_=-]{64}(?![A-Za-z0-9_=-])/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC314", "CI job token GitLab", 798, "secrets", /\bglcbt-[A-Za-z0-9]{1,5}_[A-Za-z0-9_-]{20}(?![A-Za-z0-9_-])/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC315", "Deploy token GitLab", 798, "secrets", /\bgldt-[A-Za-z0-9_-]{20}(?![A-Za-z0-9_-])/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC316", "Incoming mail token GitLab", 798, "secrets", /\bglimt-[A-Za-z0-9_-]{25}(?![A-Za-z0-9_-])/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC317", "Kubernetes agent token GitLab", 798, "secrets", /\bglagent-[A-Za-z0-9_-]{50}(?![A-Za-z0-9_-])/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC318", "OAuth application secret GitLab", 798, "secrets", /\bgloas-[A-Za-z0-9_-]{64}(?![A-Za-z0-9_-])/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC319", "Pipeline trigger token GitLab", 798, "secrets", /\bglptt-[a-f0-9]{40}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC320", "Legacy runner registration token GitLab", 798, "secrets", /\bGR1348941[A-Za-z0-9_-]{20}(?![A-Za-z0-9_-])/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC321", "Runner authentication token GitLab", 798, "secrets", /\bglrt-[A-Za-z0-9_-]{20}(?![A-Za-z0-9_-])/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC322", "SCIM token GitLab", 798, "secrets", /\bglsoat-[A-Za-z0-9_-]{20}(?![A-Za-z0-9_-])/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC323", "Cloud API token Grafana", 798, "secrets", /\bglc_[A-Za-z0-9+/]{32,400}={0,3}(?![A-Za-z0-9+/=])/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC324", "API key Harness", 798, "secrets", /\b(?:pat|sat)\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9]{24}\.[A-Za-z0-9]{20}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC325", "API token Terraform Cloud", 798, "secrets", /\b[A-Za-z0-9]{14}\.atlasv1\.[A-Za-z0-9_=-]{60,70}(?![A-Za-z0-9_=-])/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC326", "API key Heroku v2", 798, "secrets", /\bHRKU-AA[A-Za-z0-9_-]{58}(?![A-Za-z0-9_-])/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC327", "Access token Hugging Face", 798, "secrets", /\bhf_[A-Za-z]{34}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC328", "Organization token Hugging Face", 798, "secrets", /\bapi_org_[A-Za-z]{34}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC329", "API token Infracost", 798, "secrets", /\bico-[A-Za-z0-9]{32}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC330", "Client secret Intra42", 798, "secrets", /\bs-s4t2(?:ud|af)-[a-f0-9]{64}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC331", "API key Linear", 798, "secrets", /\blin_api_[A-Za-z0-9]{40}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC332", "API token Notion", 798, "secrets", /\bntn_[0-9]{11}[A-Za-z0-9]{35}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC333", "API key Octopus Deploy", 798, "secrets", /\bAPI-[A-Z0-9]{26}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC334", "API key Perplexity", 798, "secrets", /\bpplx-[A-Za-z0-9]{48}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC335", "API token PlanetScale", 798, "secrets", /\bpscale_tkn_[A-Za-z0-9_.=-]{32,64}(?![A-Za-z0-9_.=-])/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC336", "OAuth token PlanetScale", 798, "secrets", /\bpscale_oauth_[A-Za-z0-9_.=-]{32,64}(?![A-Za-z0-9_.=-])/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC337", "Пароль PlanetScale", 798, "secrets", /\bpscale_pw_[A-Za-z0-9_.=-]{32,64}(?![A-Za-z0-9_.=-])/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC338", "API token Prefect", 798, "secrets", /\bpnu_[A-Za-z0-9]{36}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
    ["SEC339", "API token RubyGems", 798, "secrets", /\brubygems_[a-f0-9]{48}\b/, "Отзовите найденный токен или смените ключ/пароль, проверьте доступ и загрузите новое значение из хранилища секретов.", "https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml"],
  ],
  JS: [
    ["JS300", "Fastify сериализует HTTP schema", 94, "injection", /\.compileSerializationSchema\s*\(\s*(?:req|request)\./, "Безопасная альтернатива: reply.compileSerializationSchema(profileSchema); Проверьте доверие к данным и применимость настройки в production."],
    ["JS301", "Fastify валидатор HTTP schema", 94, "injection", /\.compileValidationSchema\s*\(\s*(?:req|request)\./, "Безопасная альтернатива: request.compileValidationSchema(profileSchema); Проверьте доверие к данным и применимость настройки в production."],
    ["JS302", "AJV компилирует HTTP schema", 94, "injection", /\bajv\.compile\s*\(\s*(?:req|request)\./, "Безопасная альтернатива: ajv.compile(profileSchema); Проверьте доверие к данным и применимость настройки в production."],
    ["JS303", "Express выбирает HTTP view", 22, "validation", /\b(?:res|response)\.render\s*\(\s*(?:req|request)\./, "Безопасная альтернатива: res.render('profile', model); Проверьте доверие к данным и применимость настройки в production."],
    ["JS304", "Pug renderFile HTTP путь", 22, "validation", /\bpug\.renderFile\s*\(\s*(?:req|request)\./, "Безопасная альтернатива: pug.renderFile(approvedTemplate); Проверьте доверие к данным и применимость настройки в production."],
    ["JS305", "EJS renderFile HTTP путь", 22, "validation", /\bejs\.renderFile\s*\(\s*(?:req|request)\./, "Безопасная альтернатива: ejs.renderFile(approvedTemplate); Проверьте доверие к данным и применимость настройки в production."],
    ["JS306", "Nunjucks render HTTP имя", 22, "validation", /\bnunjucks\.render\s*\(\s*(?:req|request)\./, "Безопасная альтернатива: nunjucks.render('profile.njk', model); Проверьте доверие к данным и применимость настройки в production."],
    ["JS307", "Sequelize fn HTTP функция", 89, "injection", /\b(?:Sequelize|sequelize)\.fn\s*\(\s*(?:req|request)\./, "Безопасная альтернатива: Sequelize.fn('COUNT', col); Проверьте доверие к данным и применимость настройки в production."],
    ["JS308", "Knex orderByRaw HTTP строка", 89, "injection", /\.orderByRaw\s*\(\s*(?:req|request)\./, "Безопасная альтернатива: query.orderBy('created_at', 'desc'); Проверьте доверие к данным и применимость настройки в production."],
    ["JS309", "Knex whereRaw HTTP строка", 89, "injection", /\.whereRaw\s*\(\s*(?:req|request)\./, "Безопасная альтернатива: query.where('id', validatedId); Проверьте доверие к данным и применимость настройки в production."],
    ["JS310", "Knex havingRaw HTTP строка", 89, "injection", /\.havingRaw\s*\(\s*(?:req|request)\./, "Безопасная альтернатива: query.having('count', '>', validatedCount); Проверьте доверие к данным и применимость настройки в production."],
    ["JS311", "Knex joinRaw HTTP строка", 89, "injection", /\.joinRaw\s*\(\s*(?:req|request)\./, "Безопасная альтернатива: query.join('profiles', 'profiles.id', 'users.id'); Проверьте доверие к данным и применимость настройки в production."],
    ["JS312", "TypeORM orderBy HTTP выражение", 89, "injection", /\b(?:qb|queryBuilder)\.orderBy\s*\(\s*(?:req|request)\./, "Безопасная альтернатива: qb.orderBy('user.createdAt', 'DESC'); Проверьте доверие к данным и применимость настройки в production."],
    ["JS313", "TypeORM addSelect HTTP выражение", 89, "injection", /\b(?:qb|queryBuilder)\.addSelect\s*\(\s*(?:req|request)\./, "Безопасная альтернатива: qb.addSelect('user.name'); Проверьте доверие к данным и применимость настройки в production."],
    ["JS314", "Needle HTTP URL", 918, "ssrf", /\bneedle\.get\s*\(\s*(?:req|request)\./, "Безопасная альтернатива: needle.get(allowedUrl, callback); Проверьте доверие к данным и применимость настройки в production."],
    ["JS315", "Node net.connect HTTP адрес", 918, "ssrf", /\bnet\.connect\s*\(\s*\{[^}\n]{0,150}\bhost\s*:\s*(?:req|request)\./, "Безопасная альтернатива: net.connect({ host: allowedHost, port: 443 }); Проверьте доверие к данным и применимость настройки в production."],
    ["JS316", "Got HTTP URL", 918, "ssrf", /\bgot\s*\(\s*(?:req|request)\./, "Безопасная альтернатива: got(allowedUrl); Проверьте доверие к данным и применимость настройки в production."],
    ["JS317", "Undici HTTP URL", 918, "ssrf", /\bundici\.request\s*\(\s*(?:req|request)\./, "Безопасная альтернатива: undici.request(allowedUrl); Проверьте доверие к данным и применимость настройки в production."],
    ["JS318", "Superagent HTTP URL", 918, "ssrf", /\bsuperagent\.get\s*\(\s*(?:req|request)\./, "Безопасная альтернатива: superagent.get(allowedUrl); Проверьте доверие к данным и применимость настройки в production."],
    ["JS319", "WebSocket HTTP адрес", 918, "ssrf", /\bnew\s+WebSocket\s*\(\s*(?:req|request)\./, "Безопасная альтернатива: new WebSocket(allowedUrl); Проверьте доверие к данным и применимость настройки в production."],
    ["JS320", "Socket.IO слишком большой HTTP buffer", 400, "validation", /\bmaxHttpBufferSize\s*:\s*1e9\b/, "Безопасная альтернатива: new Server({ maxHttpBufferSize: 65536 }); Проверьте доверие к данным и применимость настройки в production."],
    ["JS321", "Multer не ограничивает fileSize", 400, "validation", /\bfileSize\s*:\s*Infinity\b/, "Безопасная альтернатива: multer({ limits: { fileSize: 1048576 } }); Проверьте доверие к данным и применимость настройки в production."],
    ["JS322", "Crypto scrypt отключает стоимость", 916, "crypto", /\bscrypt(?:Sync)?\s*\([^\n]{0,250}\bN\s*:\s*(?:2|4|8|16)\b/, "Безопасная альтернатива: crypto.scryptSync(password, salt, 32, calibratedParameters); Проверьте доверие к данным и применимость настройки в production."],
    ["JS323", "Node RSA PKCS1 v1.5 padding", 780, "crypto", /\bpadding\s*:\s*crypto\.constants\.RSA_PKCS1_PADDING\b/, "Безопасная альтернатива: crypto.publicEncrypt({ key, padding: crypto.constants.RSA_PKCS1_OAEP_PADDING }, data); Проверьте доверие к данным и применимость настройки в production."],
    ["JS324", "JWT допускает слабые RSA ключи", 326, "transport", /\ballowInsecureKeySizes\s*:\s*true\b/, "Безопасная альтернатива: jwt.sign(payload, strongKey, { algorithm: 'RS256', allowInsecureKeySizes: false }); Проверьте доверие к данным и применимость настройки в production."],
  ],
  PY: [
    ["PY300", "Python os.spawnl HTTP executable", 78, "injection", /\bos\.spawnl\s*\([^,\n]+,\s*request\./, "Безопасная альтернатива: run_allowed_program(program_id) Проверьте доверие к данным и применимость настройки в production."],
    ["PY301", "Python os.posix_spawn HTTP executable", 78, "injection", /\bos\.posix_spawn\s*\(\s*request\./, "Безопасная альтернатива: os.posix_spawn('/usr/bin/tool', checked_argv, clean_env) Проверьте доверие к данным и применимость настройки в production."],
    ["PY302", "Python subprocess cwd HTTP путь", 22, "validation", /\bcwd\s*=\s*request\.(?:args|form|json|values)\b/, "Безопасная альтернатива: subprocess.run(['/usr/bin/tool'], cwd=allowed_directory) Проверьте доверие к данным и применимость настройки в production."],
    ["PY303", "Python ctypes загружает HTTP библиотеку", 829, "injection", /\bctypes\.CDLL\s*\(\s*request\./, "Безопасная альтернатива: ctypes.CDLL(approved_library) Проверьте доверие к данным и применимость настройки в production."],
    ["PY304", "Python ctypes PyDLL HTTP библиотека", 829, "injection", /\bctypes\.PyDLL\s*\(\s*request\./, "Безопасная альтернатива: ctypes.PyDLL(approved_library) Проверьте доверие к данным и применимость настройки в production."],
    ["PY305", "Python import spec HTTP путь", 829, "injection", /\bimportlib\.util\.spec_from_file_location\s*\([^,\n]+,\s*request\./, "Безопасная альтернатива: importlib.util.spec_from_file_location('plugin', approved_path) Проверьте доверие к данным и применимость настройки в production."],
    ["PY306", "Python Pydantic обходит HTTP validation", 20, "validation", /\.model_construct\s*\(\s*\*\*request\./, "Безопасная альтернатива: Profile.model_validate(request.json) Проверьте доверие к данным и применимость настройки в production."],
    ["PY307", "Python Jinja from_string HTTP шаблон", 1336, "injection", /\.from_string\s*\(\s*request\./, "Безопасная альтернатива: environment.get_template('profile.html') Проверьте доверие к данным и применимость настройки в production."],
    ["PY308", "Python Bottle SimpleTemplate HTTP шаблон", 1336, "injection", /\bSimpleTemplate\s*\(\s*source\s*=\s*request\./, "Безопасная альтернатива: SimpleTemplate(name='profile') Проверьте доверие к данным и применимость настройки в production."],
    ["PY309", "Python Tornado HTTP template path", 22, "validation", /\bself\.render\s*\(\s*self\.get_argument\s*\(/, "Безопасная альтернатива: self.render('profile.html') Проверьте доверие к данным и применимость настройки в production."],
    ["PY310", "Python Django database raw cursor", 89, "injection", /\bcursor\.executescript\s*\(\s*request\./, "Безопасная альтернатива: cursor.execute('select * from users where id=?', [id]) Проверьте доверие к данным и применимость настройки в production."],
    ["PY311", "Python psycopg AsIs HTTP SQL", 89, "injection", /\bAsIs\s*\(\s*request\./, "Безопасная альтернатива: sql.Identifier(allowed_column) Проверьте доверие к данным и применимость настройки в production."],
    ["PY312", "Python SQLAlchemy literal_column HTTP", 89, "injection", /\bliteral_column\s*\(\s*request\./, "Безопасная альтернатива: table.c.name Проверьте доверие к данным и применимость настройки в production."],
    ["PY313", "Python Psycopg SQL HTTP строка", 89, "injection", /\b(?:psycopg\.)?sql\.SQL\s*\(\s*request\./, "Безопасная альтернатива: sql.SQL('SELECT * FROM users WHERE id = %s') Проверьте доверие к данным и применимость настройки в production."],
    ["PY314", "Python Peewee SQL HTTP", 89, "injection", /\bpeewee\.SQL\s*\(\s*request\./, "Безопасная альтернатива: User.id == validated_id Проверьте доверие к данным и применимость настройки в production."],
    ["PY315", "Python LDAP search HTTP фильтр", 90, "injection", /\.search_s\s*\([^\n]{0,200}\brequest\.(?:args|form)\b/, "Безопасная альтернатива: conn.search_s(base, ldap.SCOPE_SUBTREE, escaped_filter) Проверьте доверие к данным и применимость настройки в production."],
    ["PY316", "Python pymongo $where HTTP", 943, "injection", /['"]\$where['"]\s*:\s*request\./, "Безопасная альтернатива: users.find({'id': validated_id}) Проверьте доверие к данным и применимость настройки в production."],
    ["PY317", "Python shutil copyfile HTTP путь", 22, "validation", /\bshutil\.copyfile\s*\(\s*request\./, "Безопасная альтернатива: shutil.copyfile(allowed_source, destination) Проверьте доверие к данным и применимость настройки в production."],
    ["PY318", "Python pathlib unlink HTTP путь", 22, "validation", /\bPath\s*\(\s*request\.[^\n]{0,150}\)\.unlink\s*\(/, "Безопасная альтернатива: allowed_path.unlink() Проверьте доверие к данным и применимость настройки в production."],
    ["PY319", "Python ZipFile HTTP архив", 22, "validation", /\bzipfile\.ZipFile\s*\(\s*request\./, "Безопасная альтернатива: zipfile.ZipFile(approved_upload) Проверьте доверие к данным и применимость настройки в production."],
    ["PY320", "Python socket HTTP адрес", 918, "ssrf", /\bsocket\.create_connection\s*\(\s*\(\s*request\./, "Безопасная альтернатива: socket.create_connection((allowed_host, 443)) Проверьте доверие к данным и применимость настройки в production."],
    ["PY321", "Python ftplib HTTP host", 918, "ssrf", /\bftplib\.FTP\s*\(\s*request\./, "Безопасная альтернатива: ftplib.FTP(allowed_host) Проверьте доверие к данным и применимость настройки в production."],
    ["PY322", "Python PBKDF2 мало итераций", 916, "crypto", /\bhashlib\.pbkdf2_hmac\s*\([^,\n]+,[^,\n]+,[^,\n]+,\s*(?:100|1000)\s*[,)]/, "Безопасная альтернатива: hashlib.pbkdf2_hmac('sha256', password, salt, calibrated_iterations) Проверьте доверие к данным и применимость настройки в production."],
    ["PY323", "Python Argon2 отключает time_cost", 916, "crypto", /\bPasswordHasher\s*\([^\n)]*\btime_cost\s*=\s*1\b/, "Безопасная альтернатива: PasswordHasher(time_cost=calibrated_cost, memory_cost=calibrated_memory) Проверьте доверие к данным и применимость настройки в production."],
    ["PY324", "Python логирует HTTP session cookie", 532, "logging", /\blogger\.(?:info|debug)\s*\(\s*request\.cookies\b/, "Безопасная альтернатива: logger.info('request completed') Проверьте доверие к данным и применимость настройки в production."],
  ],
  JAVA: [
    ["JAVA300", "Java JEXL createScript HTTP код", 917, "injection", /\.createScript\s*\(\s*request\.getParameter\s*\(/, "Безопасная альтернатива: dispatchAllowedAction(action); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA301", "Java SpEL parseRaw HTTP выражение", 917, "injection", /\.parseRaw\s*\(\s*request\.getParameter\s*\(/, "Безопасная альтернатива: parser.parseRaw(\"profile.name\"); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA302", "Java BeanShell source HTTP файл", 94, "injection", /\b(?:interpreter|bsh)\.source\s*\(\s*request\.getParameter\s*\(/, "Безопасная альтернатива: dispatchAllowedAction(action); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA303", "Java BeanUtils mass assignment HTTP", 915, "injection", /\bBeanUtils\.populate\s*\([^,\n]+,\s*request\.getParameterMap\s*\(/, "Безопасная альтернатива: BeanUtils.populate(user, allowedFields); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA304", "Java Grape dependency HTTP координаты", 829, "injection", /\bGrape\.grab\s*\(\s*request\./, "Безопасная альтернатива: loadApprovedDependency(dependencyId); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA305", "Java XML external general entities", 611, "xxe", /\.setFeature\s*\(\s*"http:\/\/xml\.org\/sax\/features\/external-general-entities"\s*,\s*true/, "Безопасная альтернатива: factory.setFeature(\"http://xml.org/sax/features/external-general-entities\", false); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA306", "Java XML external parameter entities", 611, "xxe", /\.setFeature\s*\(\s*"http:\/\/xml\.org\/sax\/features\/external-parameter-entities"\s*,\s*true/, "Безопасная альтернатива: factory.setFeature(\"http://xml.org/sax/features/external-parameter-entities\", false); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA307", "Java XML загружает external DTD", 611, "xxe", /\.setFeature\s*\(\s*"http:\/\/apache\.org\/xml\/features\/nonvalidating\/load-external-dtd"\s*,\s*true/, "Безопасная альтернатива: factory.setFeature(\"http://apache.org/xml/features/nonvalidating/load-external-dtd\", false); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA308", "Java XML отключает secure processing", 611, "xxe", /\.setFeature\s*\(\s*XMLConstants\.FEATURE_SECURE_PROCESSING\s*,\s*false/, "Безопасная альтернатива: factory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA309", "Java XML external schema unrestricted", 611, "xxe", /\.setProperty\s*\(\s*XMLConstants\.ACCESS_EXTERNAL_SCHEMA\s*,\s*"all"/, "Безопасная альтернатива: schema.setProperty(XMLConstants.ACCESS_EXTERNAL_SCHEMA, \"\"); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA310", "Java XML external DTD unrestricted", 611, "xxe", /\.setAttribute\s*\(\s*XMLConstants\.ACCESS_EXTERNAL_DTD\s*,\s*"all"/, "Безопасная альтернатива: factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, \"\"); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA311", "Java Netty доверяет всем certificates", 295, "transport", /\bInsecureTrustManagerFactory\.INSTANCE\b/, "Безопасная альтернатива: SslContextBuilder.forClient().trustManager(caFile); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA312", "Java Kafka отключает hostname check", 297, "transport", /"ssl\.endpoint\.identification\.algorithm"\s*,\s*""/, "Безопасная альтернатива: props.put(\"ssl.endpoint.identification.algorithm\", \"https\"); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA313", "Java TLS явно включает TLSv1", 326, "transport", /\.setEnabledProtocols\s*\(\s*new\s+String\[\]\s*\{\s*"TLSv1"/, "Безопасная альтернатива: socket.setEnabledProtocols(new String[]{\"TLSv1.3\"}); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA314", "Java BCrypt низкая стоимость", 916, "crypto", /\bnew\s+BCryptPasswordEncoder\s*\(\s*[4-9]\s*\)/, "Безопасная альтернатива: new BCryptPasswordEncoder(calibratedCost); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA315", "Java PBKDF2 низкие iterations", 916, "crypto", /\bnew\s+PBEKeySpec\s*\([^,\n]+,[^,\n]+,\s*(?:100|1000)\s*,/, "Безопасная альтернатива: new PBEKeySpec(password, salt, calibratedIterations, 256); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA316", "Java scrypt низкий CPU cost", 916, "crypto", /\bnew\s+SCryptPasswordEncoder\s*\(\s*(?:2|4|8|16)\s*,/, "Безопасная альтернатива: new SCryptPasswordEncoder(calibratedN, 8, 1, 32, 16); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA317", "Java Spring CORS setAllowedOrigins wildcard", 942, "configuration", /\.setAllowedOrigins\s*\(\s*(?:List\.of|Arrays\.asList)\s*\(\s*"\*"/, "Безопасная альтернатива: cors.setAllowedOrigins(List.of(\"https://app.example\")); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA318", "Java Spring CORS all Origin", 942, "configuration", /@CrossOrigin\s*\(\s*origins\s*=\s*"\*"/, "Безопасная альтернатива: @CrossOrigin(origins = \"https://app.example\") Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA319", "Java RedirectView HTTP URL", 601, "validation", /\bnew\s+RedirectView\s*\(\s*request\.getParameter\s*\(/, "Безопасная альтернатива: new RedirectView(\"/home\"); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA320", "Java JAX-RS location HTTP URL", 601, "validation", /\.location\s*\(\s*URI\.create\s*\(\s*request\.getParameter\s*\(/, "Безопасная альтернатива: Response.status(302).location(URI.create(\"/home\")); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA321", "Java FileUtils HTTP URL", 918, "ssrf", /\bFileUtils\.copyURLToFile\s*\(\s*new\s+URL\s*\(\s*userUrl\b/, "Безопасная альтернатива: FileUtils.copyURLToFile(new URL(allowedUrl), target); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA322", "Java Apache HttpGet HTTP URL", 918, "ssrf", /\bnew\s+HttpGet\s*\(\s*request\.getParameter\s*\(/, "Безопасная альтернатива: new HttpGet(allowedUrl); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA323", "Java Socket HTTP host", 918, "ssrf", /\bnew\s+Socket\s*\(\s*request\.getParameter\s*\(/, "Безопасная альтернатива: new Socket(allowedHost, 443); Проверьте доверие к данным и применимость настройки в production."],
    ["JAVA324", "Java logger раскрывает HTTP cookies", 532, "logging", /\blogger\.(?:info|debug)\s*\(\s*request\.getCookies\s*\(/, "Безопасная альтернатива: logger.info(\"request completed\"); Проверьте доверие к данным и применимость настройки в production."],
  ],
  PHP: [
    ["PHP300", "PHP Laravel selectRaw HTTP строка", 89, "injection", /->selectRaw\s*\(\s*\$_(?:GET|POST|REQUEST)/, "Безопасная альтернатива: $query->select(['id', 'name']); Проверьте доверие к данным и применимость настройки в production."],
    ["PHP301", "PHP Laravel havingRaw HTTP строка", 89, "injection", /->havingRaw\s*\(\s*\$_(?:GET|POST|REQUEST)/, "Безопасная альтернатива: $query->having('count', '>', $validatedCount); Проверьте доверие к данным и применимость настройки в production."],
    ["PHP302", "PHP Laravel groupByRaw HTTP строка", 89, "injection", /->groupByRaw\s*\(\s*\$_(?:GET|POST|REQUEST)/, "Безопасная альтернатива: $query->groupBy('country'); Проверьте доверие к данным и применимость настройки в production."],
    ["PHP303", "PHP Doctrine DQL HTTP строка", 564, "injection", /->createQuery\s*\(\s*\$_(?:GET|POST|REQUEST)/, "Безопасная альтернатива: $em->createQuery('SELECT u FROM User u WHERE u.id = :id'); Проверьте доверие к данным и применимость настройки в production."],
    ["PHP304", "PHP Doctrine DBAL HTTP SQL", 89, "injection", /->executeQuery\s*\(\s*\$_(?:GET|POST|REQUEST)/, "Безопасная альтернатива: $db->executeQuery('SELECT * FROM users WHERE id = ?', [$id]); Проверьте доверие к данным и применимость настройки в production."],
    ["PHP305", "PHP Doctrine executeStatement HTTP SQL", 89, "injection", /->executeStatement\s*\(\s*\$_(?:GET|POST|REQUEST)/, "Безопасная альтернатива: $db->executeStatement('DELETE FROM users WHERE id = ?', [$id]); Проверьте доверие к данным и применимость настройки в production."],
    ["PHP306", "PHP Twig load HTTP шаблон", 22, "validation", /\$twig->load\s*\(\s*\$_(?:GET|POST|REQUEST)/, "Безопасная альтернатива: $twig->load('profile.html.twig'); Проверьте доверие к данным и применимость настройки в production."],
    ["PHP307", "PHP Smarty fetch HTTP шаблон", 22, "validation", /\$smarty->fetch\s*\(\s*\$_(?:GET|POST|REQUEST)/, "Безопасная альтернатива: $smarty->fetch('profile.tpl'); Проверьте доверие к данным и применимость настройки в production."],
    ["PHP308", "PHP file HTTP путь", 22, "validation", /\bfile\s*\(\s*\$_(?:GET|POST|REQUEST)/, "Безопасная альтернатива: file($allowedPath); Проверьте доверие к данным и применимость настройки в production."],
    ["PHP309", "PHP stream_socket_client HTTP адрес", 918, "ssrf", /\bstream_socket_client\s*\(\s*\$_(?:GET|POST|REQUEST)/, "Безопасная альтернатива: stream_socket_client($allowedAddress); Проверьте доверие к данным и применимость настройки в production."],
    ["PHP310", "PHP fsockopen HTTP host", 918, "ssrf", /\bfsockopen\s*\(\s*\$_(?:GET|POST|REQUEST)/, "Безопасная альтернатива: fsockopen($allowedHost, 443); Проверьте доверие к данным и применимость настройки в production."],
    ["PHP311", "PHP ftp_connect HTTP host", 918, "ssrf", /\bftp_connect\s*\(\s*\$_(?:GET|POST|REQUEST)/, "Безопасная альтернатива: ftp_connect($allowedHost); Проверьте доверие к данным и применимость настройки в production."],
    ["PHP312", "PHP ZipArchive extractTo HTTP каталог", 22, "validation", /->extractTo\s*\(\s*\$_(?:GET|POST|REQUEST)/, "Безопасная альтернатива: extract_checked_entries($zip, $allowedDirectory); Проверьте доверие к данным и применимость настройки в production."],
    ["PHP313", "PHP rename HTTP назначение", 22, "validation", /\brename\s*\([^,\n]+,\s*\$_(?:GET|POST|REQUEST)/, "Безопасная альтернатива: rename($source, $allowedPath); Проверьте доверие к данным и применимость настройки в production."],
    ["PHP314", "PHP chmod HTTP путь", 22, "validation", /\bchmod\s*\(\s*\$_(?:GET|POST|REQUEST)/, "Безопасная альтернатива: chmod($allowedPath, 0600); Проверьте доверие к данным и применимость настройки в production."],
    ["PHP315", "PHP chown HTTP путь", 22, "validation", /\bchown\s*\(\s*\$_(?:GET|POST|REQUEST)/, "Безопасная альтернатива: chown($allowedPath, $owner); Проверьте доверие к данным и применимость настройки в production."],
    ["PHP316", "PHP password_hash слабый Argon2 memory", 916, "crypto", /['"]memory_cost['"]\s*=>\s*(?:8|16|32|64|128|256|512|1024)\b/, "Безопасная альтернатива: password_hash($password, PASSWORD_ARGON2ID, ['memory_cost' => $calibratedMemory]); Проверьте доверие к данным и применимость настройки в production."],
    ["PHP317", "PHP hash_pbkdf2 мало iterations", 916, "crypto", /\bhash_pbkdf2\s*\([^,\n]+,[^,\n]+,[^,\n]+,\s*(?:100|1000)\s*[,)]/, "Безопасная альтернатива: hash_pbkdf2('sha256', $password, $salt, $calibratedIterations); Проверьте доверие к данным и применимость настройки в production."],
    ["PHP318", "PHP session cookie SameSite None", 1275, "csrf", /\bsession_set_cookie_params\s*\([^\n]{0,200}['"]samesite['"]\s*=>\s*['"]None['"]/, "Безопасная альтернатива: session_set_cookie_params(['samesite' => 'Strict', 'secure' => true]); Проверьте доверие к данным и применимость настройки в production."],
    ["PHP319", "PHP логирует HTTP cookies", 532, "logging", /\berror_log\s*\(\s*(?:json_encode|print_r)\s*\(\s*\$_COOKIE\b/, "Безопасная альтернатива: error_log('request completed'); Проверьте доверие к данным и применимость настройки в production."],
  ],
  GO: [
    ["GO300", "Go GORM Group HTTP SQL", 89, "injection", /\.Group\s*\(\s*c\.Query\s*\(/, "Безопасная альтернатива: db.Group(\"country\") Проверьте доверие к данным и применимость настройки в production."],
    ["GO301", "Go GORM Joins HTTP SQL", 89, "injection", /\.Joins\s*\(\s*c\.Query\s*\(/, "Безопасная альтернатива: db.Joins(\"Profile\") Проверьте доверие к данным и применимость настройки в production."],
    ["GO302", "Go GORM Having HTTP SQL", 89, "injection", /\.Having\s*\(\s*c\.Query\s*\(/, "Безопасная альтернатива: db.Having(\"count > ?\", validatedCount) Проверьте доверие к данным и применимость настройки в production."],
    ["GO303", "Go GORM Pluck HTTP колонка", 89, "injection", /\.Pluck\s*\(\s*c\.Query\s*\(/, "Безопасная альтернатива: db.Pluck(\"name\", &values) Проверьте доверие к данным и применимость настройки в production."],
    ["GO304", "Go GORM Table HTTP таблица", 89, "injection", /\.Table\s*\(\s*c\.Query\s*\(/, "Безопасная альтернатива: db.Table(\"users\") Проверьте доверие к данным и применимость настройки в production."],
    ["GO305", "Go HTTP NewRequestWithContext HTTP URL", 918, "ssrf", /\bhttp\.NewRequestWithContext\s*\([^,\n]+,[^,\n]+,\s*r\.URL\.Query\s*\(/, "Безопасная альтернатива: http.NewRequestWithContext(ctx, \"GET\", allowedURL, nil) Проверьте доверие к данным и применимость настройки в production."],
    ["GO306", "Go net.DialTimeout HTTP адрес", 918, "ssrf", /\bnet\.DialTimeout\s*\([^,\n]+,\s*r\.URL\.Query\s*\(/, "Безопасная альтернатива: net.DialTimeout(\"tcp\", allowedAddress, timeout) Проверьте доверие к данным и применимость настройки в production."],
    ["GO307", "Go Resty HTTP URL", 918, "ssrf", /\.R\s*\(\s*\)\.Get\s*\(\s*c\.Query\s*\(/, "Безопасная альтернатива: client.R().Get(allowedURL) Проверьте доверие к данным и применимость настройки в production."],
    ["GO308", "Go HTTP PostForm HTTP URL", 918, "ssrf", /\bhttp\.PostForm\s*\(\s*c\.Query\s*\(/, "Безопасная альтернатива: http.PostForm(allowedURL, values) Проверьте доверие к данным и применимость настройки в production."],
    ["GO309", "Go Gin Redirect HTTP URL", 601, "validation", /\bc\.Redirect\s*\([^,\n]+,\s*c\.Query\s*\(/, "Безопасная альтернатива: c.Redirect(302, \"/home\") Проверьте доверие к данным и применимость настройки в production."],
    ["GO310", "Go Echo File HTTP путь", 22, "validation", /\bc\.File\s*\(\s*c\.QueryParam\s*\(/, "Безопасная альтернатива: c.File(allowedPath) Проверьте доверие к данным и применимость настройки в production."],
    ["GO311", "Go Echo Attachment HTTP путь", 22, "validation", /\bc\.Attachment\s*\(\s*c\.QueryParam\s*\(/, "Безопасная альтернатива: c.Attachment(allowedPath, \"download\") Проверьте доверие к данным и применимость настройки в production."],
    ["GO312", "Go Echo Inline HTTP путь", 22, "validation", /\bc\.Inline\s*\(\s*c\.QueryParam\s*\(/, "Безопасная альтернатива: c.Inline(allowedPath, \"document\") Проверьте доверие к данным и применимость настройки в production."],
    ["GO313", "Go os.Rename HTTP назначение", 22, "validation", /\bos\.Rename\s*\([^,\n]+,\s*r\.URL\.Query\s*\(/, "Безопасная альтернатива: os.Rename(source, allowedPath) Проверьте доверие к данным и применимость настройки в production."],
    ["GO314", "Go os.Chmod HTTP путь", 22, "validation", /\bos\.Chmod\s*\(\s*r\.URL\.Query\s*\(/, "Безопасная альтернатива: os.Chmod(allowedPath, 0600) Проверьте доверие к данным и применимость настройки в production."],
    ["GO315", "Go os.Chown HTTP путь", 22, "validation", /\bos\.Chown\s*\(\s*r\.URL\.Query\s*\(/, "Безопасная альтернатива: os.Chown(allowedPath, uid, gid) Проверьте доверие к данным и применимость настройки в production."],
    ["GO316", "Go syscall.Exec HTTP executable", 78, "injection", /\bsyscall\.Exec\s*\(\s*c\.Query\s*\(/, "Безопасная альтернатива: syscall.Exec(\"/usr/bin/tool\", checkedArgv, cleanEnv) Проверьте доверие к данным и применимость настройки в production."],
    ["GO317", "Go scrypt слабая стоимость", 916, "crypto", /\bscrypt\.Key\s*\([^,\n]+,[^,\n]+,\s*(?:2|4|8|16)\s*,/, "Безопасная альтернатива: scrypt.Key(password, salt, calibratedN, 8, 1, 32) Проверьте доверие к данным и применимость настройки в production."],
    ["GO318", "Go PBKDF2 слабая стоимость", 916, "crypto", /\bpbkdf2\.Key\s*\([^,\n]+,[^,\n]+,\s*(?:100|1000)\s*,/, "Безопасная альтернатива: pbkdf2.Key(password, salt, calibratedIterations, 32, sha256.New) Проверьте доверие к данным и применимость настройки в production."],
    ["GO319", "Go Argon2 низкая память", 916, "crypto", /\bargon2\.IDKey\s*\([^,\n]+,[^,\n]+,[^,\n]+,\s*(?:8|16|32|64|128|256|512|1024)\s*,/, "Безопасная альтернатива: argon2.IDKey(password, salt, calibratedTime, calibratedMemory, 1, 32) Проверьте доверие к данным и применимость настройки в production."],
  ],
  CS: [
    ["CS300", ".NET File.Move HTTP назначение", 22, "validation", /\bFile\.Move\s*\([^,\n]+,\s*(?:request|Request)\./, "Безопасная альтернатива: File.Move(source, allowedPath); Проверьте доверие к данным и применимость настройки в production."],
    ["CS301", ".NET File.Copy HTTP источник", 22, "validation", /\bFile\.Copy\s*\(\s*(?:request|Request)\./, "Безопасная альтернатива: File.Copy(allowedSource, destination); Проверьте доверие к данным и применимость настройки в production."],
    ["CS302", ".NET File.AppendAllText HTTP путь", 22, "validation", /\bFile\.AppendAllText\s*\(\s*(?:request|Request)\./, "Безопасная альтернатива: File.AppendAllText(allowedPath, data); Проверьте доверие к данным и применимость настройки в production."],
    ["CS303", ".NET Directory.CreateDirectory HTTP", 22, "validation", /\bDirectory\.CreateDirectory\s*\(\s*(?:request|Request)\./, "Безопасная альтернатива: Directory.CreateDirectory(allowedPath); Проверьте доверие к данным и применимость настройки в production."],
    ["CS304", ".NET ZipFile.ExtractToDirectory HTTP", 22, "validation", /\bZipFile\.ExtractToDirectory\s*\([^,\n]+,\s*(?:request|Request)\./, "Безопасная альтернатива: ExtractValidatedEntries(upload, allowedDirectory); Проверьте доверие к данным и применимость настройки в production."],
    ["CS305", ".NET NativeLibrary.Load HTTP библиотека", 829, "injection", /\bNativeLibrary\.Load\s*\(\s*(?:request|Request)\./, "Безопасная альтернатива: NativeLibrary.Load(approvedLibrary); Проверьте доверие к данным и применимость настройки в production."],
    ["CS306", ".NET Assembly.LoadFile HTTP библиотека", 829, "injection", /\bAssembly\.LoadFile\s*\(\s*(?:request|Request)\./, "Безопасная альтернатива: Assembly.LoadFile(approvedAssembly); Проверьте доверие к данным и применимость настройки в production."],
    ["CS307", ".NET Type.GetType HTTP класс", 470, "injection", /\bType\.GetType\s*\(\s*(?:request|Request)\./, "Безопасная альтернатива: allowedTypes[typeId]; Проверьте доверие к данным и применимость настройки в production."],
    ["CS308", ".NET Dynamic LINQ HTTP выражение", 943, "injection", /\bDynamicExpressionParser\.ParseLambda\s*\([^\n]{0,200}\bRequest\./, "Безопасная альтернатива: BuildAllowedFilter(validatedFields); Проверьте доверие к данным и применимость настройки в production."],
    ["CS309", ".NET SqlDataAdapter HTTP SQL", 89, "injection", /\bnew\s+SqlDataAdapter\s*\(\s*(?:request|Request)\./, "Безопасная альтернатива: new SqlDataAdapter(parameterizedCommand); Проверьте доверие к данным и применимость настройки в production."],
    ["CS310", ".NET OdbcCommand HTTP SQL", 89, "injection", /\bnew\s+OdbcCommand\s*\(\s*(?:request|Request)\./, "Безопасная альтернатива: new OdbcCommand(\"select * from users where id=?\", connection); Проверьте доверие к данным и применимость настройки в production."],
    ["CS311", ".NET OleDbCommand HTTP SQL", 89, "injection", /\bnew\s+OleDbCommand\s*\(\s*(?:request|Request)\./, "Безопасная альтернатива: new OleDbCommand(\"select * from users where id=?\", connection); Проверьте доверие к данным и применимость настройки в production."],
    ["CS312", ".NET HttpClient PostAsync HTTP URL", 918, "ssrf", /\.PostAsync\s*\(\s*(?:request|Request)\./, "Безопасная альтернатива: client.PostAsync(allowedURL, content); Проверьте доверие к данным и применимость настройки в production."],
    ["CS313", ".NET WebClient DownloadFile HTTP URL", 918, "ssrf", /\.DownloadFile\s*\(\s*(?:request|Request)\./, "Безопасная альтернатива: client.DownloadFile(allowedURL, target); Проверьте доверие к данным и применимость настройки в production."],
    ["CS314", ".NET TCP client HTTP host", 918, "ssrf", /\bnew\s+TcpClient\s*\(\s*(?:request|Request)\./, "Безопасная альтернатива: new TcpClient(allowedHost, 443); Проверьте доверие к данным и применимость настройки в production."],
    ["CS315", ".NET HttpClient DeleteAsync HTTP URL", 918, "ssrf", /\.DeleteAsync\s*\(\s*(?:request|Request)\./, "Безопасная альтернатива: client.DeleteAsync(allowedURL); Проверьте доверие к данным и применимость настройки в production."],
    ["CS316", ".NET XPathNavigator HTTP выражение", 643, "injection", /\bnavigator\.Select\s*\(\s*(?:request|Request)\./, "Безопасная альтернатива: navigator.Select(\"/users/user\"); Проверьте доверие к данным и применимость настройки в production."],
    ["CS317", ".NET XSLT разрешает script", 611, "xxe", /\bEnableScript\s*=\s*true\b/, "Безопасная альтернатива: settings.EnableScript = false; Проверьте доверие к данным и применимость настройки в production."],
    ["CS318", ".NET XSLT разрешает document()", 611, "xxe", /\bEnableDocumentFunction\s*=\s*true\b/, "Безопасная альтернатива: settings.EnableDocumentFunction = false; Проверьте доверие к данным и применимость настройки в production."],
    ["CS319", ".NET HTTP отключает TLS revocation", 295, "transport", /\bCheckCertificateRevocationList\s*=\s*false\b/, "Безопасная альтернатива: handler.CheckCertificateRevocationList = true; Проверьте доверие к данным и применимость настройки в production."],
  ],
  RB: [
    ["RB300", "Rails having HTTP SQL", 89, "injection", /\.having\s*\(\s*params\[/, "Безопасная альтернатива: User.having('count > ?', validated_count) Проверьте доверие к данным и применимость настройки в production."],
    ["RB301", "Rails from HTTP SQL", 89, "injection", /\.from\s*\(\s*params\[/, "Безопасная альтернатива: User.from('users') Проверьте доверие к данным и применимость настройки в production."],
    ["RB302", "Rails reselect HTTP SQL", 89, "injection", /\.reselect\s*\(\s*params\[/, "Безопасная альтернатива: User.reselect(:id, :name) Проверьте доверие к данным и применимость настройки в production."],
    ["RB303", "Rails rewhere raw HTTP SQL", 89, "injection", /\.where\s*\(\s*params\[:sql\]\s*\)/, "Безопасная альтернатива: User.where(name: validated_name) Проверьте доверие к данным и применимость настройки в production."],
    ["RB304", "RubyVM загружает HTTP bytecode", 502, "deserialization", /\bRubyVM::InstructionSequence\.load_from_binary\s*\(\s*params\[/, "Безопасная альтернатива: JSON.parse(params[:data]) Проверьте доверие к данным и применимость настройки в production."],
    ["RB305", "Ruby Dir.glob HTTP путь", 22, "validation", /\bDir\.glob\s*\(\s*params\[/, "Безопасная альтернатива: Dir.glob(allowed_pattern) Проверьте доверие к данным и применимость настройки в production."],
    ["RB306", "Ruby FileUtils rm_rf HTTP путь", 22, "validation", /\bFileUtils\.rm_rf\s*\(\s*params\[/, "Безопасная альтернатива: FileUtils.rm_rf(allowed_directory) Проверьте доверие к данным и применимость настройки в production."],
    ["RB307", "Ruby FileUtils cp HTTP путь", 22, "validation", /\bFileUtils\.cp\s*\(\s*params\[/, "Безопасная альтернатива: FileUtils.cp(allowed_source, target) Проверьте доверие к данным и применимость настройки в production."],
    ["RB308", "Ruby FileUtils mv HTTP назначение", 22, "validation", /\bFileUtils\.mv\s*\([^,\n]+,\s*params\[/, "Безопасная альтернатива: FileUtils.mv(source, allowed_path) Проверьте доверие к данным и применимость настройки в production."],
    ["RB309", "Ruby TCPSocket HTTP адрес", 918, "ssrf", /\bTCPSocket\.new\s*\(\s*params\[/, "Безопасная альтернатива: TCPSocket.new(allowed_host, 443) Проверьте доверие к данным и применимость настройки в production."],
    ["RB310", "Ruby Socket.tcp HTTP адрес", 918, "ssrf", /\bSocket\.tcp\s*\(\s*params\[/, "Безопасная альтернатива: Socket.tcp(allowed_host, 443) Проверьте доверие к данным и применимость настройки в production."],
    ["RB311", "Ruby Net HTTP post_form HTTP URL", 918, "ssrf", /\bNet::HTTP\.post_form\s*\(\s*URI\s*\(\s*params\[/, "Безопасная альтернатива: Net::HTTP.post_form(URI(allowed_url), values) Проверьте доверие к данным и применимость настройки в production."],
    ["RB312", "Ruby OpenSSL security level ноль", 326, "transport", /\.security_level\s*=\s*0\b/, "Безопасная альтернатива: context.security_level = 2 Проверьте доверие к данным и применимость настройки в production."],
    ["RB313", "Ruby PBKDF2 низкие iterations", 916, "crypto", /\bOpenSSL::KDF\.pbkdf2_hmac\s*\([^\n]{0,250}\biterations:\s*(?:100|1000)\b/, "Безопасная альтернатива: OpenSSL::KDF.pbkdf2_hmac(password, salt: salt, iterations: calibrated_iterations, length: 32, hash: 'sha256') Проверьте доверие к данным и применимость настройки в production."],
    ["RB314", "Ruby scrypt низкая стоимость", 916, "crypto", /\bOpenSSL::KDF\.scrypt\s*\([^\n]{0,250}\bN:\s*(?:2|4|8|16)\b/, "Безопасная альтернатива: OpenSSL::KDF.scrypt(password, salt: salt, N: calibrated_n, r: 8, p: 1, length: 32) Проверьте доверие к данным и применимость настройки в production."],
  ],
  RS: [
    ["RS300", "Rust HTTP body без практического лимита", 400, "validation", /\bRequestBodyLimitLayer::new\s*\(\s*usize::MAX\s*\)/, "Безопасная альтернатива: RequestBodyLimitLayer::new(1048576); Проверьте доверие к данным и применимость настройки в production."],
    ["RS301", "Rust OpenSSL security level ноль", 326, "transport", /\.set_security_level\s*\(\s*0\s*\)/, "Безопасная альтернатива: builder.set_security_level(2); Проверьте доверие к данным и применимость настройки в production."],
    ["RS302", "Rust RSA crate слабый ключ", 326, "transport", /\bRsaPrivateKey::new\s*\([^,\n]+,\s*(?:512|768|1024)\s*\)/, "Безопасная альтернатива: RsaPrivateKey::new(&mut rng, 3072); Проверьте доверие к данным и применимость настройки в production."],
    ["RS303", "Rust bcrypt низкая стоимость", 916, "crypto", /\bbcrypt::hash\s*\([^,\n]+,\s*[4-9]\s*\)/, "Безопасная альтернатива: bcrypt::hash(password, calibrated_cost); Проверьте доверие к данным и применимость настройки в production."],
    ["RS304", "Rust scrypt low log_n", 916, "crypto", /\bscrypt::Params::new\s*\(\s*[1-9]\s*,/, "Безопасная альтернатива: scrypt::Params::new(calibrated_log_n, 8, 1, 32); Проверьте доверие к данным и применимость настройки в production."],
    ["RS305", "Rust PBKDF2 низкие iterations", 916, "crypto", /\bpbkdf2_hmac(?:_array)?(?:::\s*<[^>]+>)?\s*\([^,\n]+,[^,\n]+,\s*(?:100|1000)\s*[,)]/, "Безопасная альтернатива: pbkdf2_hmac::<Sha256>(password, salt, calibrated_iterations, &mut key); Проверьте доверие к данным и применимость настройки в production."],
    ["RS306", "Rust libloading HTTP библиотека", 829, "injection", /\bLibrary::new\s*\(\s*(?:query\.library|user_library)\b/, "Безопасная альтернатива: unsafe { Library::new(approved_library) }; Проверьте доверие к данным и применимость настройки в production."],
    ["RS307", "Rust SQLx QueryBuilder raw push HTTP", 89, "injection", /\b(?:builder|query_builder)\.push\s*\(\s*query\.(?:sql|filter|order)\b/, "Безопасная альтернатива: query_builder.push_bind(validated_value); Проверьте доверие к данным и применимость настройки в production."],
    ["RS308", "Rust Tokio file HTTP путь", 22, "validation", /\btokio::fs::read\s*\(\s*query\.path\b/, "Безопасная альтернатива: tokio::fs::read(allowed_path).await; Проверьте доверие к данным и применимость настройки в production."],
    ["RS309", "Rust Tokio remove HTTP каталог", 22, "validation", /\btokio::fs::remove_dir_all\s*\(\s*query\.path\b/, "Безопасная альтернатива: tokio::fs::remove_dir_all(allowed_directory).await; Проверьте доверие к данным и применимость настройки в production."],
    ["RS310", "Rust std file write HTTP путь", 22, "validation", /\bstd::fs::write\s*\(\s*query\.path\b/, "Безопасная альтернатива: std::fs::write(allowed_path, data); Проверьте доверие к данным и применимость настройки в production."],
    ["RS311", "Rust reqwest HTTP query URL", 918, "ssrf", /\breqwest::get\s*\(\s*query\.url\b/, "Безопасная альтернатива: reqwest::get(allowed_url).await; Проверьте доверие к данным и применимость настройки в production."],
    ["RS312", "Rust TcpStream HTTP адрес", 918, "ssrf", /\bTcpStream::connect\s*\(\s*query\.address\b/, "Безопасная альтернатива: TcpStream::connect(allowed_address); Проверьте доверие к данным и применимость настройки в production."],
    ["RS313", "Rust Tera HTTP template text", 1336, "injection", /\bTera::one_off\s*\(\s*&?query\.template\b/, "Безопасная альтернатива: tera.render(\"profile.html\", &context); Проверьте доверие к данным и применимость настройки в production."],
    ["RS314", "Rust UTF-8 mutable unchecked", 20, "validation", /\bstr::from_utf8_unchecked_mut\s*\(/, "Безопасная альтернатива: std::str::from_utf8_mut(user_bytes)?; Проверьте доверие к данным и применимость настройки в production."],
  ],
  SWIFT: [
    ["SWIFT300", "Swift RSA signature SHA1", 327, "crypto", /\bSecKeyAlgorithm\.rsaSignatureMessagePKCS1v15SHA1\b/, "Безопасная альтернатива: SecKeyCreateSignature(key, SecKeyAlgorithm.rsaSignatureMessagePSSSHA256, data, &error) Проверьте доверие к данным и применимость настройки в production."],
    ["SWIFT301", "Swift URLSession ограничивает max TLS", 326, "transport", /\.tlsMaximumSupportedProtocolVersion\s*=\s*\.TLSv11\b/, "Безопасная альтернатива: configuration.tlsMaximumSupportedProtocolVersion = .TLSv13 Проверьте доверие к данным и применимость настройки в production."],
    ["SWIFT302", "Swift NSPredicate HTTP выражение", 943, "injection", /\bNSPredicate\s*\(\s*format:\s*userInput\b/, "Безопасная альтернатива: NSPredicate(format: \"name == %@\", validatedName) Проверьте доверие к данным и применимость настройки в production."],
    ["SWIFT303", "Swift NSExpression внешний код", 95, "injection", /\bNSExpression\s*\(\s*format:\s*userInput\b/, "Безопасная альтернатива: NSExpression(forConstantValue: validatedValue) Проверьте доверие к данным и применимость настройки в production."],
    ["SWIFT304", "Swift удаляет внешний путь", 22, "validation", /\.removeItem\s*\(\s*atPath:\s*userPath\b/, "Безопасная альтернатива: FileManager.default.removeItem(atPath: allowedPath) Проверьте доверие к данным и применимость настройки в production."],
    ["SWIFT305", "Swift копирует внешний путь", 22, "validation", /\.copyItem\s*\(\s*atPath:\s*userPath\b/, "Безопасная альтернатива: FileManager.default.copyItem(atPath: allowedSource, toPath: destination) Проверьте доверие к данным и применимость настройки в production."],
    ["SWIFT306", "Swift URLSession внешний URL", 918, "ssrf", /\.dataTask\s*\(\s*with:\s*URL\s*\(\s*string:\s*userUrl\b/, "Безопасная альтернатива: URLSession.shared.dataTask(with: allowedUrl) Проверьте доверие к данным и применимость настройки в production."],
    ["SWIFT307", "Swift os_log публичный пароль", 532, "logging", /\bos_log\s*\(\s*"%\{public\}@"\s*,\s*password\b/, "Безопасная альтернатива: os_log(\"authentication completed\") Проверьте доверие к данным и применимость настройки в production."],
    ["SWIFT308", "Swift Regex внешний шаблон", 1333, "validation", /\bNSRegularExpression\s*\(\s*pattern:\s*userInput\b/, "Безопасная альтернатива: NSRegularExpression(pattern: NSRegularExpression.escapedPattern(for: userInput)) Проверьте доверие к данным и применимость настройки в production."],
    ["SWIFT309", "Swift WebView снимает app-bound navigation", 693, "configuration", /\.limitsNavigationsToAppBoundDomains\s*=\s*false\b/, "Безопасная альтернатива: configuration.limitsNavigationsToAppBoundDomains = true Проверьте доверие к данным и применимость настройки в production."],
  ],
  SCALA: [
    ["SCALA300", "Scala JEXL HTTP script", 917, "injection", /\.createScript\s*\(\s*request\.getQueryString\s*\(/, "Безопасная альтернатива: dispatchAllowedAction(action) Проверьте доверие к данным и применимость настройки в production."],
    ["SCALA301", "Scala MVEL HTTP выражение", 917, "injection", /\bMVEL\.compileExpression\s*\(\s*request\.getQueryString\s*\(/, "Безопасная альтернатива: dispatchAllowedAction(action) Проверьте доверие к данным и применимость настройки в production."],
    ["SCALA302", "Scala OGNL HTTP выражение", 917, "injection", /\bOgnl\.parseExpression\s*\(\s*request\.getQueryString\s*\(/, "Безопасная альтернатива: Ognl.parseExpression(\"profile.name\") Проверьте доверие к данным и применимость настройки в production."],
    ["SCALA303", "Scala ClassLoader HTTP класс", 470, "injection", /\.loadClass\s*\(\s*request\.getQueryString\s*\(/, "Безопасная альтернатива: allowedClasses(classId) Проверьте доверие к данным и применимость настройки в production."],
    ["SCALA304", "Scala Netty trust-all factory", 295, "transport", /\bInsecureTrustManagerFactory\.INSTANCE\b/, "Безопасная альтернатива: builder.trustManager(caFile) Проверьте доверие к данным и применимость настройки в production."],
    ["SCALA305", "Scala слабый RSA key spec", 326, "transport", /\bnew\s+RSAKeyGenParameterSpec\s*\(\s*(?:512|768|1024)\s*,/, "Безопасная альтернатива: new RSAKeyGenParameterSpec(3072, RSAKeyGenParameterSpec.F4) Проверьте доверие к данным и применимость настройки в production."],
    ["SCALA306", "Scala BCrypt слабая стоимость", 916, "crypto", /\bBCrypt\.gensalt\s*\(\s*[4-9]\s*\)/, "Безопасная альтернатива: BCrypt.gensalt(calibratedCost) Проверьте доверие к данным и применимость настройки в production."],
    ["SCALA307", "Scala Files HTTP move destination", 22, "validation", /\bFiles\.move\s*\([^,\n]+,\s*Paths\.get\s*\(\s*request\./, "Безопасная альтернатива: Files.move(source, allowedPath) Проверьте доверие к данным и применимость настройки в production."],
    ["SCALA308", "Scala Socket HTTP host", 918, "ssrf", /\bnew\s+Socket\s*\(\s*request\.getQueryString\s*\(/, "Безопасная альтернатива: new Socket(allowedHost, 443) Проверьте доверие к данным и применимость настройки в production."],
    ["SCALA309", "Scala Play WS HTTP URL", 918, "ssrf", /\bws\.url\s*\(\s*request\.getQueryString\s*\(/, "Безопасная альтернатива: ws.url(allowedUrl).get() Проверьте доверие к данным и применимость настройки в production."],
  ],
  SH: [
    ["SH300", "AWS CLI отключает certificate check", 295, "transport", /\baws\b[^\n]*--no-verify-ssl\b/, "Безопасная альтернатива: aws s3 ls --ca-bundle ca.pem Проверьте доверие к данным и применимость настройки в production."],
    ["SH301", "Gcloud отключает certificate check", 295, "transport", /\bgcloud\s+config\s+set\s+auth\/disable_ssl_validation\s+true\b/, "Безопасная альтернатива: gcloud config set auth/disable_ssl_validation false Проверьте доверие к данным и применимость настройки в production."],
    ["SH302", "Ansible отключает SSH host checking", 295, "transport", /\bANSIBLE_HOST_KEY_CHECKING\s*=\s*False\b/, "Безопасная альтернатива: ANSIBLE_HOST_KEY_CHECKING=True ansible-playbook deploy.yml Проверьте доверие к данным и применимость настройки в production."],
    ["SH303", "Git environment отключает TLS trust", 295, "transport", /\bGIT_SSL_NO_VERIFY\s*=\s*(?:true|1)\b/, "Безопасная альтернатива: git -c http.sslVerify=true fetch Проверьте доверие к данным и применимость настройки в production."],
    ["SH304", "Python environment отключает HTTPS trust", 295, "transport", /\bPYTHONHTTPSVERIFY\s*=\s*0\b/, "Безопасная альтернатива: python app.py Проверьте доверие к данным и применимость настройки в production."],
    ["SH305", "Node environment отключает TLS trust", 295, "transport", /\bNODE_TLS_REJECT_UNAUTHORIZED\s*=\s*0\b/, "Безопасная альтернатива: node app.js Проверьте доверие к данным и применимость настройки в production."],
    ["SH306", "Node CLI insecure HTTP parser", 444, "validation", /\bnode\b[^\n]*--insecure-http-parser\b/, "Безопасная альтернатива: node app.js Проверьте доверие к данным и применимость настройки в production."],
    ["SH307", "Node CLI включает legacy provider", 327, "crypto", /\bnode\b[^\n]*--openssl-legacy-provider\b/, "Безопасная альтернатива: node app.js Проверьте доверие к данным и применимость настройки в production."],
    ["SH308", "Install создаёт world writable файл", 732, "authorization", /\binstall\s+-m\s+0?777\b/, "Безопасная альтернатива: install -m 0750 app /srv/app Проверьте доверие к данным и применимость настройки в production."],
    ["SH309", "Rsync разрешает всем запись", 732, "authorization", /\brsync\b[^\n]*--chmod=ugo=rwX\b/, "Безопасная альтернатива: rsync --chmod=Du=rwx,Dgo=,Fu=rw,Fgo= src/ dst/ Проверьте доверие к данным и применимость настройки в production."],
    ["SH310", "OpenSSL req сохраняет key без encryption", 312, "crypto", /\bopenssl\s+req\b[^\n]*-nodes\b/, "Безопасная альтернатива: openssl req -new -keyout protected-key.pem Проверьте доверие к данным и применимость настройки в production."],
    ["SH311", "OpenSSL PKCS12 выводит plaintext key", 312, "crypto", /\bopenssl\s+pkcs12\b[^\n]*-nodes\b/, "Безопасная альтернатива: openssl pkcs12 -in bundle.p12 Проверьте доверие к данным и применимость настройки в production."],
    ["SH312", "Psql sslmode allow допускает plaintext", 319, "transport", /\bpsql\b[^\n]*sslmode=allow\b/, "Безопасная альтернатива: psql 'host=db.example sslmode=verify-full' Проверьте доверие к данным и применимость настройки в production."],
    ["SH313", "MySQL CLI отключает TLS", 319, "transport", /\bmysql\b[^\n]*--ssl-mode=DISABLED\b/, "Безопасная альтернатива: mysql --ssl-mode=VERIFY_IDENTITY -h db.example Проверьте доверие к данным и применимость настройки в production."],
    ["SH314", "Redis CLI plaintext URI", 319, "transport", /\bredis-cli\b[^\n]*\s-u\s+redis:\/\//, "Безопасная альтернатива: redis-cli -u rediss://db.example:6379 Проверьте доверие к данным и применимость настройки в production."],
  ],
  CFG: [
    ["CFG300", "Terraform S3 отключает public access block", 284, "authorization", /\b(?:block_public_acls|ignore_public_acls|block_public_policy|restrict_public_buckets)\s*=\s*false\b/, "Безопасная альтернатива: block_public_acls = true Проверьте доверие к данным и применимость настройки в production."],
    ["CFG301", "Terraform KMS отключает key rotation", 320, "crypto", /\benable_key_rotation\s*=\s*false\b/, "Безопасная альтернатива: enable_key_rotation = true Проверьте доверие к данным и применимость настройки в production."],
    ["CFG302", "Terraform CloudTrail отключает logging", 778, "logging", /\benable_logging\s*=\s*false\b/, "Безопасная альтернатива: enable_logging = true Проверьте доверие к данным и применимость настройки в production."],
    ["CFG303", "CloudFront viewer допускает HTTP", 319, "transport", /\bviewer_protocol_policy\s*=\s*"allow-all"/, "Безопасная альтернатива: viewer_protocol_policy = \"https-only\" Проверьте доверие к данным и применимость настройки в production."],
    ["CFG304", "CloudFront origin использует HTTP", 319, "transport", /\borigin_protocol_policy\s*=\s*"http-only"/, "Безопасная альтернатива: origin_protocol_policy = \"https-only\" Проверьте доверие к данным и применимость настройки в production."],
    ["CFG305", "CloudFront устаревший минимум TLS", 326, "transport", /\bminimum_protocol_version\s*=\s*"TLSv1"/, "Безопасная альтернатива: minimum_protocol_version = \"TLSv1.2_2021\" Проверьте доверие к данным и применимость настройки в production."],
    ["CFG306", "Lambda function URL без authentication", 306, "authentication", /\bauthorization_type\s*=\s*"NONE"/, "Безопасная альтернатива: authorization_type = \"AWS_IAM\" Проверьте доверие к данным и применимость настройки в production."],
    ["CFG307", "API Gateway метод без authorization", 306, "authentication", /\bauthorization\s*=\s*"NONE"/, "Безопасная альтернатива: authorization = \"AWS_IAM\" Проверьте доверие к данным и применимость настройки в production."],
    ["CFG308", "IAM Allow с публичным Principal", 284, "authorization", /"Effect"\s*:\s*"Allow"[^}\n]{0,200}"Principal"\s*:\s*"\*"/, "Безопасная альтернатива: {\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::123456789012:role/reader\"},\"Action\":\"s3:GetObject\"} Проверьте доверие к данным и применимость настройки в production."],
    ["CFG309", "IAM PassRole разрешает все ресурсы", 250, "authorization", /"Action"\s*:\s*"iam:PassRole"[^}\n]{0,150}"Resource"\s*:\s*"\*"/, "Безопасная альтернатива: {\"Effect\":\"Allow\",\"Action\":\"iam:PassRole\",\"Resource\":\"arn:aws:iam::123456789012:role/app\"} Проверьте доверие к данным и применимость настройки в production."],
    ["CFG310", "IAM слишком короткие пароли", 287, "authentication", /\bminimum_password_length\s*=\s*[1-7]\b/, "Безопасная альтернатива: minimum_password_length = 16 Проверьте доверие к данным и применимость настройки в production."],
    ["CFG311", "Terraform RDS без deletion protection", 1188, "configuration", /\bdeletion_protection\s*=\s*false\b/, "Безопасная альтернатива: deletion_protection = true Проверьте доверие к данным и применимость настройки в production."],
    ["CFG312", "MSK разрешает unauthenticated clients", 306, "authentication", /\bunauthenticated\s*=\s*true\b/, "Безопасная альтернатива: client_authentication { unauthenticated = false } Проверьте доверие к данным и применимость настройки в production."],
    ["CFG313", "MSK plaintext client broker", 319, "transport", /\bclient_broker\s*=\s*"PLAINTEXT"/, "Безопасная альтернатива: client_broker = \"TLS\" Проверьте доверие к данным и применимость настройки в production."],
    ["CFG314", "Terraform MQ публичный broker", 284, "authorization", /\bpublicly_accessible\s*=\s*true\b/, "Безопасная альтернатива: publicly_accessible = false Проверьте доверие к данным и применимость настройки в production."],
    ["CFG315", "Terraform удаляет непустой storage", 1188, "configuration", /\bforce_destroy\s*=\s*true\b/, "Безопасная альтернатива: force_destroy = false Проверьте доверие к данным и применимость настройки в production."],
    ["CFG316", "Azure App Service не требует HTTPS", 319, "transport", /\bhttps_only\s*=\s*false\b/, "Безопасная альтернатива: https_only = true Проверьте доверие к данным и применимость настройки в production."],
    ["CFG317", "Azure App Service допускает plain FTP", 319, "transport", /\bftps_state\s*=\s*"AllAllowed"/, "Безопасная альтернатива: ftps_state = \"FtpsOnly\" Проверьте доверие к данным и применимость настройки в production."],
    ["CFG318", "Azure App Service remote debugging", 200, "configuration", /\bremote_debugging_enabled\s*=\s*true\b/, "Безопасная альтернатива: remote_debugging_enabled = false Проверьте доверие к данным и применимость настройки в production."],
    ["CFG319", "Azure storage публичные nested items", 284, "authorization", /\ballow_nested_items_to_be_public\s*=\s*true\b/, "Безопасная альтернатива: allow_nested_items_to_be_public = false Проверьте доверие к данным и применимость настройки в production."],
    ["CFG320", "Azure Container Registry admin account", 287, "authentication", /\badmin_enabled\s*=\s*true\b/, "Безопасная альтернатива: admin_enabled = false Проверьте доверие к данным и применимость настройки в production."],
    ["CFG321", "Azure Container Registry anonymous pull", 306, "authentication", /\banonymous_pull_enabled\s*=\s*true\b/, "Безопасная альтернатива: anonymous_pull_enabled = false Проверьте доверие к данным и применимость настройки в production."],
    ["CFG322", "GCP firewall открыт всему IPv6", 284, "authorization", /\bsource_ranges\s*=\s*\[[^\]\n]{0,200}"::\/0"/, "Безопасная альтернатива: source_ranges = [\"2001:db8:1234::/64\"] Проверьте доверие к данным и применимость настройки в production."],
    ["CFG323", "GCP IAM выдаёт доступ всем users", 284, "authorization", /\bmember\s*=\s*"(?:allUsers|allAuthenticatedUsers)"/, "Безопасная альтернатива: member = \"serviceAccount:app@example.iam.gserviceaccount.com\" Проверьте доверие к данным и применимость настройки в production."],
    ["CFG324", "GCP Cloud Run публичный ingress", 284, "authorization", /\bingress\s*=\s*"INGRESS_TRAFFIC_ALL"/, "Безопасная альтернатива: ingress = \"INGRESS_TRAFFIC_INTERNAL_ONLY\" Проверьте доверие к данным и применимость настройки в production."],
    ["CFG325", "GCP VM без secure boot", 693, "configuration", /\benable_secure_boot\s*=\s*false\b/, "Безопасная альтернатива: enable_secure_boot = true Проверьте доверие к данным и применимость настройки в production."],
    ["CFG326", "GCP VM без vTPM", 693, "configuration", /\benable_vtpm\s*=\s*false\b/, "Безопасная альтернатива: enable_vtpm = true Проверьте доверие к данным и применимость настройки в production."],
    ["CFG327", "GCP VM без integrity monitoring", 778, "logging", /\benable_integrity_monitoring\s*=\s*false\b/, "Безопасная альтернатива: enable_integrity_monitoring = true Проверьте доверие к данным и применимость настройки в production."],
    ["CFG328", "GCP GKE без shielded nodes", 693, "configuration", /\benable_shielded_nodes\s*=\s*false\b/, "Безопасная альтернатива: enable_shielded_nodes = true Проверьте доверие к данным и применимость настройки в production."],
    ["CFG329", "GCP VM разрешает project SSH keys", 284, "authorization", /"block-project-ssh-keys"\s*=\s*"false"/, "Безопасная альтернатива: \"block-project-ssh-keys\" = \"true\" Проверьте доверие к данным и применимость настройки в production."],
    ["CFG330", "GCP VM открывает serial console", 200, "configuration", /"serial-port-enable"\s*=\s*"true"/, "Безопасная альтернатива: \"serial-port-enable\" = \"false\" Проверьте доверие к данным и применимость настройки в production."],
    ["CFG331", "GCP VM допускает legacy metadata", 918, "ssrf", /"disable-legacy-endpoints"\s*=\s*"false"/, "Безопасная альтернатива: \"disable-legacy-endpoints\" = \"true\" Проверьте доверие к данным и применимость настройки в production."],
    ["CFG332", "PostgreSQL HBA trust без пароля", 306, "authentication", /^\s*host\s+\S+\s+\S+\s+\S+\s+trust\b/, "Безопасная альтернатива: hostssl all all 10.0.0.0/8 scram-sha-256 Проверьте доверие к данным и применимость настройки в production."],
    ["CFG333", "PostgreSQL сервер отключает SSL", 319, "transport", /^\s*ssl\s*=\s*off\b/, "Безопасная альтернатива: ssl = on Проверьте доверие к данным и применимость настройки в production."],
    ["CFG334", "PostgreSQL пишет все SQL в log", 532, "logging", /^\s*log_statement\s*=\s*'all'/, "Безопасная альтернатива: log_statement = 'ddl' Проверьте доверие к данным и применимость настройки в production."],
    ["CFG335", "MySQL включает local infile", 73, "validation", /^\s*local_infile\s*=\s*(?:ON|1)\b/, "Безопасная альтернатива: local_infile = OFF Проверьте доверие к данным и применимость настройки в production."],
    ["CFG336", "MySQL не ограничивает file import/export", 73, "validation", /^\s*secure_file_priv\s*=\s*""/, "Безопасная альтернатива: secure_file_priv = \"/var/lib/mysql-files\" Проверьте доверие к данным и применимость настройки в production."],
    ["CFG337", "MySQL разрешает plaintext connections", 319, "transport", /^\s*require_secure_transport\s*=\s*(?:OFF|0)\b/, "Безопасная альтернатива: require_secure_transport = ON Проверьте доверие к данным и применимость настройки в production."],
    ["CFG338", "MySQL пишет все запросы в general log", 532, "logging", /^\s*general_log\s*=\s*(?:ON|1)\b/, "Безопасная альтернатива: general_log = OFF Проверьте доверие к данным и применимость настройки в production."],
    ["CFG339", "Redis убирает default пароль", 306, "authentication", /^\s*requirepass\s+""/, "Безопасная альтернатива: include /run/secrets/redis-auth.conf Проверьте доверие к данным и применимость настройки в production."],
    ["CFG340", "MongoDB отключает TLS mode", 319, "transport", /\btls\s*:\s*\{[^}\n]{0,150}\bmode\s*:\s*disabled\b/, "Безопасная альтернатива: tls: { mode: requireTLS } Проверьте доверие к данным и применимость настройки в production."],
    ["CFG341", "RabbitMQ guest вне loopback", 306, "authentication", /\bloopback_users\s*=\s*\[\s*\]/, "Безопасная альтернатива: loopback_users.guest = true Проверьте доверие к данным и применимость настройки в production."],
    ["CFG342", "RabbitMQ отключает проверку peer TLS", 295, "transport", /\bssl_options\.verify\s*=\s*verify_none\b/, "Безопасная альтернатива: ssl_options.verify = verify_peer Проверьте доверие к данным и применимость настройки в production."],
    ["CFG343", "Kafka открывает ресурсы без ACL", 862, "authorization", /\ballow\.everyone\.if\.no\.acl\.found\s*=\s*true\b/, "Безопасная альтернатива: allow.everyone.if.no.acl.found = false Проверьте доверие к данным и применимость настройки в production."],
    ["CFG344", "Kafka plaintext listener", 319, "transport", /\blisteners\s*=\s*PLAINTEXT:\/\//, "Безопасная альтернатива: listeners = SASL_SSL://broker.example:9093 Проверьте доверие к данным и применимость настройки в production."],
    ["CFG345", "Elasticsearch HTTP без TLS", 319, "transport", /\bxpack\.security\.http\.ssl\.enabled\s*:\s*false\b/, "Безопасная альтернатива: xpack.security.http.ssl.enabled: true Проверьте доверие к данным и применимость настройки в production."],
    ["CFG346", "Elasticsearch cluster без TLS", 319, "transport", /\bxpack\.security\.transport\.ssl\.enabled\s*:\s*false\b/, "Безопасная альтернатива: xpack.security.transport.ssl.enabled: true Проверьте доверие к данным и применимость настройки в production."],
    ["CFG347", "OpenSearch отключает security plugin", 306, "authentication", /\bplugins\.security\.disabled\s*:\s*true\b/, "Безопасная альтернатива: plugins.security.disabled: false Проверьте доверие к данным и применимость настройки в production."],
    ["CFG348", "Grafana anonymous access", 306, "authentication", /\bGF_AUTH_ANONYMOUS_ENABLED\s*=\s*true\b/, "Безопасная альтернатива: GF_AUTH_ANONYMOUS_ENABLED=false Проверьте доверие к данным и применимость настройки в production."],
    ["CFG349", "Grafana cookie без Secure", 614, "authentication", /\bGF_SECURITY_COOKIE_SECURE\s*=\s*false\b/, "Безопасная альтернатива: GF_SECURITY_COOKIE_SECURE=true Проверьте доверие к данным и применимость настройки в production."],
    ["CFG350", "Grafana cookie SameSite none", 1275, "csrf", /\bGF_SECURITY_COOKIE_SAMESITE\s*=\s*none\b/, "Безопасная альтернатива: GF_SECURITY_COOKIE_SAMESITE=strict Проверьте доверие к данным и применимость настройки в production."],
    ["CFG351", "Grafana разрешает embedding", 1021, "configuration", /\bGF_SECURITY_ALLOW_EMBEDDING\s*=\s*true\b/, "Безопасная альтернатива: GF_SECURITY_ALLOW_EMBEDDING=false Проверьте доверие к данным и применимость настройки в production."],
    ["CFG352", "Consul отключает TLS verification", 295, "transport", /\b(?:verify_incoming|verify_outgoing)\s*=\s*false\b/, "Безопасная альтернатива: verify_outgoing = true Проверьте доверие к данным и применимость настройки в production."],
    ["CFG353", "Vault отключает listener TLS", 319, "transport", /\btls_disable\s*=\s*(?:1|true)\b/, "Безопасная альтернатива: tls_disable = 0 Проверьте доверие к данным и применимость настройки в production."],
    ["CFG354", "Traefik insecure API", 306, "authentication", /\bapi\s*:\s*\{[^}\n]{0,150}\binsecure\s*:\s*true\b/, "Безопасная альтернатива: api: { insecure: false } Проверьте доверие к данным и применимость настройки в production."],
    ["CFG355", "Jenkins отключает authentication", 306, "authentication", /<useSecurity>\s*false\s*<\/useSecurity>/, "Безопасная альтернатива: <useSecurity>true</useSecurity> Проверьте доверие к данным и применимость настройки в production."],
    ["CFG356", "SonarQube legacy authentication off", 306, "authentication", /\bsonar\.forceAuthentication\s*=\s*false\b/, "Безопасная альтернатива: sonar.forceAuthentication=true Проверьте доверие к данным и применимость настройки в production."],
    ["CFG357", "Docker отключает SELinux labels", 693, "configuration", /\bsecurity_opt\s*:\s*\[[^\]\n]{0,150}"label=disable"/, "Безопасная альтернатива: security_opt: [\"label=type:container_t\"] Проверьте доверие к данным и применимость настройки в production."],
    ["CFG358", "Apache отключает upstream TLS verify", 295, "transport", /\bSSLProxyVerify\s+none\b/, "Безопасная альтернатива: SSLProxyVerify require Проверьте доверие к данным и применимость настройки в production."],
    ["CFG359", "Spring Actuator публикует env values", 200, "configuration", /\bmanagement\.endpoint\.env\.show-values\s*=\s*ALWAYS\b/, "Безопасная альтернатива: management.endpoint.env.show-values=NEVER Проверьте доверие к данным и применимость настройки в production."],
  ],
};

const languages: Record<string, string[]> = {
  "SEC": [
    "javascript",
    "typescript",
    "python",
    "java",
    "kotlin",
    "php",
    "go",
    "csharp",
    "ruby",
    "rust",
    "swift",
    "scala",
    "shell",
    "config",
    "unknown"
  ],
  "JS": [
    "javascript",
    "typescript"
  ],
  "PY": [
    "python"
  ],
  "JAVA": [
    "java",
    "kotlin"
  ],
  "PHP": [
    "php"
  ],
  "GO": [
    "go"
  ],
  "CS": [
    "csharp"
  ],
  "RB": [
    "ruby"
  ],
  "RS": [
    "rust"
  ],
  "SWIFT": [
    "swift"
  ],
  "SCALA": [
    "scala"
  ],
  "SH": [
    "shell"
  ],
  "CFG": [
    "config"
  ]
};
const categoryInfo: Record<string, [string, string]> = {
  "secrets": [
    "A07:2021",
    "Узнаваемый формат credential требует проверки утечки и отзыва; действительность токена по сети не проверяется."
  ],
  "injection": [
    "A03:2021",
    "Недоверенные данные могут изменить выполняемый запрос, код или выбираемую операцию."
  ],
  "xss": [
    "A03:2021",
    "При выводе недоверенных данных в HTML необходима проверка контекста и экранирования."
  ],
  "deserialization": [
    "A08:2021",
    "Недоверенные объекты могут вызвать выполнение кода или неконтролируемое потребление ресурсов."
  ],
  "transport": [
    "A02:2021",
    "Настройка ослабляет аутентификацию узла или защиту сетевого соединения."
  ],
  "crypto": [
    "A02:2021",
    "Проверьте стойкость параметров и назначение криптографической операции."
  ],
  "validation": [
    "A01:2021",
    "Внешние пути, шаблоны или объёмы требуют проверки границ и разрешённых значений."
  ],
  "ssrf": [
    "A10:2021",
    "Внешний ввод выбирает сетевой узел; проверьте IP, схему, порты и перенаправления."
  ],
  "authentication": [
    "A07:2021",
    "Проверьте необходимость настройки и независимую защиту credentials, доступа и сессий."
  ],
  "authorization": [
    "A01:2021",
    "Настройка требует проверки минимальных привилегий и допустимых границ доступа."
  ],
  "configuration": [
    "A05:2021",
    "В production проверьте необходимость возможности, изоляцию и независимые защитные меры."
  ],
  "logging": [
    "A09:2021",
    "Журналирование требует защиты чувствительных данных и полноты событий аудита."
  ],
  "xxe": [
    "A05:2021",
    "XML функции могут разрешить внешние ресурсы или расширение сущностей."
  ],
  "csrf": [
    "A01:2021",
    "При cookie-аутентификации нужна проверка защиты от поддельных запросов."
  ]
};

export function createAdvancedRules(): Rule[] {
  const critical = new Set([78, 89, 94, 95, 917, 1336]);
  const high = new Set(["xss", "deserialization", "transport", "xxe", "ssrf"]);
  return Object.entries(groups).flatMap(([family, specs]) => specs.map(([id, title, cwe, category, pattern, recommendation, reference]) => ({
    id, title, pattern, category, recommendation, languages: languages[family],
    cwe: `CWE-${cwe}`, owasp: categoryInfo[category][0],
    description: `${title}. ${categoryInfo[category][1]} Проверьте источник данных и условия применения.`,
    severity: (family === "SEC" || critical.has(cwe) ? "critical" : high.has(category) || cwe === 306 ? "high" : "medium") as Severity,
    confidence: family === "SEC" ? "high" as const : "medium" as const,
    references: [`https://cwe.mitre.org/data/definitions/${cwe}.html`, ...(reference ? [reference] : [])],
  })));
}
