"use client";

import { useCallback, useEffect, useState } from "react";

type ManagedUser = { id: string; username: string; displayName: string; role: string; isActive: boolean; mustChangePassword: boolean; lastLoginAt: string | null; createdAt: string };
export default function UsersPanel({ currentUserId }: { currentUserId: string }) {
  const [users, setUsers] = useState<ManagedUser[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [form, setForm] = useState({ username: "", displayName: "", password: "", role: "user" });
  const load = useCallback(async () => { const response = await fetch("/api/users"); if (response.ok) setUsers(await response.json() as ManagedUser[]); }, []);
  useEffect(() => { let active = true; void fetch("/api/users").then(async (response) => { if (active && response.ok) setUsers(await response.json() as ManagedUser[]); }); return () => { active = false; }; }, []);
  const create = async (event: React.FormEvent) => { event.preventDefault(); setError(""); setMessage(""); const response = await fetch("/api/users", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json() as { error?: string }; if (!response.ok) return setError(body.error ?? "Не удалось создать пользователя"); setForm({ username: "", displayName: "", password: "", role: "user" }); setMessage("Пользователь создан. При первом входе ему потребуется сменить пароль."); await load(); };
  const act = async (id: string, action: string, role?: string) => { setError(""); setMessage(""); if (action === "delete" && !window.confirm("Удалить пользователя без возможности восстановления?")) return; const response = action === "delete" ? await fetch(`/api/users?id=${encodeURIComponent(id)}`, { method: "DELETE" }) : await fetch("/api/users", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, action, role }) }); const body = response.status === 204 ? {} : await response.json() as { error?: string; temporaryPassword?: string }; if (!response.ok) return setError(body.error ?? "Операция не выполнена"); if (body.temporaryPassword) setMessage(`Временный пароль: ${body.temporaryPassword} — сохраните его сейчас, повторно он не отображается.`); await load(); };
  return <section className="users-panel" id="users"><div className="panel-header"><div><span className="panel-dot" /><div><h2>Пользователи</h2><p>Учётные записи, роли и доступ к сервису</p></div></div></div>
    <form className="user-create" onSubmit={create}><input placeholder="Логин" pattern="[a-zA-Z0-9._-]{3,64}" value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} required /><input placeholder="Имя" maxLength={120} value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })} required /><input type="password" placeholder="Пароль, минимум 10 символов" minLength={10} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} required /><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="user">Пользователь</option><option value="admin">Администратор</option></select><button>Создать</button></form>
    {(error || message) && <div className={error ? "user-message error" : "user-message"} role="status">{error || message}</div>}
    <div className="users-table"><div className="users-row users-head"><span>Пользователь</span><span>Роль</span><span>Статус</span><span>Последний вход</span><span>Действия</span></div>{users.map((user) => <div className="users-row" key={user.id}><span><strong>{user.displayName}</strong><small>{user.username}{user.id === currentUserId ? " · вы" : ""}</small></span><span><select disabled={user.id === currentUserId} value={user.role} onChange={(e) => void act(user.id, "role", e.target.value)}><option value="user">Пользователь</option><option value="admin">Администратор</option></select></span><span className={user.isActive ? "user-active" : "user-blocked"}>{user.isActive ? (user.mustChangePassword ? "Смена пароля" : "Активен") : "Заблокирован"}</span><span>{user.lastLoginAt ? new Date(user.lastLoginAt).toLocaleString("ru-RU") : "—"}</span><span className="user-actions"><button onClick={() => void act(user.id, "reset-password")}>Сбросить пароль</button>{user.id !== currentUserId && <><button onClick={() => void act(user.id, user.isActive ? "block" : "unblock")}>{user.isActive ? "Заблокировать" : "Разблокировать"}</button><button className="danger" onClick={() => void act(user.id, "delete")}>Удалить</button></>}</span></div>)}</div>
  </section>;
}
